## CAT BOOST REGRESSOR

In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()
import zipfile
import re
from scipy import stats
from catboost import CatBoostRegressor
from tqdm import tqdm
import gc
import datetime as dt

<font color = blue> Once we have imported the necessary libraries, we are going to define our data path and then, load the data: </font>

In [2]:
data_path = './data/'

In [3]:
print('Loading Properties ...')
properties2016 = pd.read_csv(data_path + 'properties_2016.csv', low_memory = False)
properties2017 = pd.read_csv(data_path + 'properties_2017.csv', low_memory = False)

Loading Properties ...

In [4]:
properties2016.head()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2015.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,650756.0,1413387.0,2015.0,762631.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,7.0,NaN,NaN,...,1.0,NaN,571346.0,1156834.0,2015.0,585488.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,NaN,NaN,193796.0,433491.0,2015.0,239695.0,5725.17,NaN,NaN,NaN

In [5]:
properties2016.shape

(2985217, 58)

In [6]:
properties2017.head()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2016.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,5.0,NaN,NaN,NaN,...,1.0,NaN,660680.0,1434941.0,2016.0,774261.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,6.0,NaN,NaN,...,1.0,NaN,580059.0,1174475.0,2016.0,594416.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,1.0,NaN,196751.0,440101.0,2016.0,243350.0,5725.17,NaN,NaN,NaN

In [7]:
properties2017.shape

(2985217, 58)

<font color = blue> We are going to specify the parameter 'parse_dates' to make the column 'transactiondate' in train files date formatted: </font>

In [8]:
print('Loading Train ...')
train2016 = pd.read_csv(data_path + 'train_2016_v2.csv', parse_dates=['transactiondate'], low_memory=False)
train2017 = pd.read_csv(data_path + 'train_2017.csv', parse_dates=['transactiondate'], low_memory=False)

Loading Train ...

In [9]:
train2016.shape

(90275, 3)

In [10]:
train2017.shape

(77613, 3)

In [11]:
train2016.head()

   parcelid  logerror transactiondate
0  11016594    0.0276      2016-01-01
1  14366692   -0.1684      2016-01-01
2  12098116   -0.0040      2016-01-01
3  12643413    0.0218      2016-01-02
4  14432541   -0.0050      2016-01-02

<font color = blue> Now we are going to parse dates to get one column for year, one for month, one for day and one for quarter: </font>

In [12]:
def add_date_features(df):
    df["transaction_year"] = df["transactiondate"].dt.year
    df["transaction_month"] = (df["transactiondate"].dt.year - 2016)*12 + df["transactiondate"].dt.month
    df["transaction_day"] = df["transactiondate"].dt.day
    df["transaction_quarter"] = (df["transactiondate"].dt.year - 2016)*4 + df["transactiondate"].dt.quarter
    df.drop(["transactiondate"], inplace=True, axis=1)
    return df

In [13]:
train2016 = add_date_features(train2016)
train2017 = add_date_features(train2017)

In [14]:
train2016.head()

,parcelid,logerror,transaction_year,transaction_month,transaction_day,transaction_quarter
0,11016594,0.0276,2016,1,1,1
1,14366692,-0.1684,2016,1,1,1
2,12098116,-0.0040,2016,1,1,1
3,12643413,0.0218,2016,1,2,1
4,14432541,-0.0050,2016,1,2,1

In [15]:
print('Loading Sample ...')
sample_submission = pd.read_csv(data_path + 'sample_submission.csv', low_memory = False)

Loading Sample ...

<font color = blue> Our sample submission will be a file with the parcel id for each property and six prediction columns for different dates (last 2016 quarter and last 2017 quarter): </font>

In [16]:
sample_submission.head()

   ParcelId  201610  201611  201612  201710  201711  201712
0  10754147       0       0       0       0       0       0
1  10759547       0       0       0       0       0       0
2  10843547       0       0       0       0       0       0
3  10859147       0       0       0       0       0       0
4  10879947       0       0       0       0       0       0

<font color = blue> As we are going to apply the first model, cat boost, to the column for 201710 predictions, we remove the other columns: </font>

In [17]:
sample_submission_model_1 = sample_submission.drop(columns = ['201610', '201611', '201612', '201711', '201712'])
sample_submission_model_1.head()

   ParcelId  201710
0  10754147       0
1  10759547       0
2  10843547       0
3  10859147       0
4  10879947       0

<font color = blue> We will merge properties and train files to get all data grouped: </font>

In [18]:
print('Merging Train with Properties ...')
train2016 = pd.merge(train2016, properties2016, how = 'left', on = 'parcelid')
train2017 = pd.merge(train2017, properties2017, how = 'left', on = 'parcelid')

Merging Train with Properties ...

In [19]:
train2016.head()

,parcelid,logerror,transaction_year,transaction_month,transaction_day,transaction_quarter,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,11016594,0.0276,2016,1,1,1,1.0,NaN,NaN,2.0,...,NaN,NaN,122754.0,360170.0,2015.0,237416.0,6735.88,NaN,NaN,6.037107e+13
1,14366692,-0.1684,2016,1,1,1,NaN,NaN,NaN,3.5,...,NaN,NaN,346458.0,585529.0,2015.0,239071.0,10153.02,NaN,NaN,NaN
2,12098116,-0.0040,2016,1,1,1,1.0,NaN,NaN,3.0,...,NaN,NaN,61994.0,119906.0,2015.0,57912.0,11484.48,NaN,NaN,6.037464e+13
3,12643413,0.0218,2016,1,2,1,1.0,NaN,NaN,2.0,...,NaN,NaN,171518.0,244880.0,2015.0,73362.0,3048.74,NaN,NaN,6.037296e+13
4,14432541,-0.0050,2016,1,2,1,NaN,NaN,NaN,2.5,...,2.0,NaN,169574.0,434551.0,2015.0,264977.0,5488.96,NaN,NaN,6.059042e+13

In [20]:
train2016.shape

(90275, 63)

In [21]:
train2017.head()

,parcelid,logerror,transaction_year,transaction_month,transaction_day,transaction_quarter,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,14297519,0.025595,2017,13,1,5,NaN,NaN,NaN,3.5,...,NaN,NaN,485713.0,1023282.0,2016.0,537569.0,11013.72,NaN,NaN,6.059063e+13
1,17052889,0.055619,2017,13,1,5,NaN,NaN,NaN,1.0,...,1.0,NaN,88000.0,464000.0,2016.0,376000.0,5672.48,NaN,NaN,6.111001e+13
2,14186244,0.005383,2017,13,1,5,NaN,NaN,NaN,2.0,...,1.0,NaN,85289.0,564778.0,2016.0,479489.0,6488.30,NaN,NaN,6.059022e+13
3,12177905,-0.103410,2017,13,1,5,NaN,NaN,NaN,3.0,...,NaN,NaN,108918.0,145143.0,2016.0,36225.0,1777.51,NaN,NaN,6.037300e+13
4,10887214,0.006940,2017,13,1,5,1.0,NaN,NaN,3.0,...,NaN,NaN,73681.0,119407.0,2016.0,45726.0,1533.89,NaN,NaN,6.037124e+13

In [22]:
train2017.shape

(77613, 63)

<font color = blue> Now we will generate our training and test files to run the model, the training file will be all properties and train from 2016 and 2017, while for the test, we will merge the sample submission with the unique properties file: </font>

In [23]:
print('Concat Train 2016 & 2017 ...')
train_df = pd.concat([train2016, train2017], axis = 0)
test_df = pd.merge(sample_submission_model_1[['ParcelId']], properties2016.rename(columns = {'parcelid': 'ParcelId'}), how = 'left', on = 'ParcelId')

Concat Train 2016 & 2017 ...

In [24]:
train_df.head()

,parcelid,logerror,transaction_year,transaction_month,transaction_day,transaction_quarter,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,11016594,0.0276,2016,1,1,1,1.0,NaN,NaN,2.0,...,NaN,NaN,122754.0,360170.0,2015.0,237416.0,6735.88,NaN,NaN,6.037107e+13
1,14366692,-0.1684,2016,1,1,1,NaN,NaN,NaN,3.5,...,NaN,NaN,346458.0,585529.0,2015.0,239071.0,10153.02,NaN,NaN,NaN
2,12098116,-0.0040,2016,1,1,1,1.0,NaN,NaN,3.0,...,NaN,NaN,61994.0,119906.0,2015.0,57912.0,11484.48,NaN,NaN,6.037464e+13
3,12643413,0.0218,2016,1,2,1,1.0,NaN,NaN,2.0,...,NaN,NaN,171518.0,244880.0,2015.0,73362.0,3048.74,NaN,NaN,6.037296e+13
4,14432541,-0.0050,2016,1,2,1,NaN,NaN,NaN,2.5,...,2.0,NaN,169574.0,434551.0,2015.0,264977.0,5488.96,NaN,NaN,6.059042e+13

In [25]:
train_df.shape

(167888, 63)

In [26]:
test_df.head()

,ParcelId,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2015.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,650756.0,1413387.0,2015.0,762631.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,7.0,NaN,NaN,...,1.0,NaN,571346.0,1156834.0,2015.0,585488.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,NaN,NaN,193796.0,433491.0,2015.0,239695.0,5725.17,NaN,NaN,NaN

In [27]:
test_df.shape

(2985217, 58)

<font color = blue> To optimize memory management, we are using garbage collections algorithms (GC), which solve reference cycles (when one or more objects are referencing each other) that reference counting cannot detect: </font>

In [28]:
del properties2016, properties2017, train2016, train2017
gc.collect();

<font color = blue> Let's do some feature engineering. We have to deal with missing values, where we will establish a threshold of 98% missing values to remove those fields, and also with features with one unique value and others that we do not want to use in our training: </font>

In [29]:
print('Missing data fields to remove ...')
missing_perc_thresh = 0.98
exclude_missing = []
num_rows = train_df.shape[0]
for c in train_df.columns:
    num_missing = train_df[c].isnull().sum()
    if num_missing == 0:
        continue
    missing_frac = num_missing / float(num_rows)
    if missing_frac > missing_perc_thresh:
        exclude_missing.append(c)
print(exclude_missing)
print("We exclude: %s" % len(exclude_missing))

Missing data fields to remove ...
['architecturalstyletypeid', 'basementsqft', 'buildingclasstypeid', 'decktypeid', 'finishedsquarefeet13', 'finishedsquarefeet6', 'poolsizesum', 'pooltypeid10', 'pooltypeid2', 'storytypeid', 'typeconstructiontypeid', 'yardbuildingsqft26', 'fireplaceflag']
We exclude: 13

In [30]:
print ("Remove features with one unique value ...")
exclude_unique = []
for c in train_df.columns:
    num_uniques = len(train_df[c].unique())
    if train_df[c].isnull().sum() != 0:
        num_uniques -= 1
    if num_uniques == 1:
        exclude_unique.append(c)
print(exclude_unique)
print("We exclude: %s" % len(exclude_unique))

Remove features with one unique value ...
['decktypeid', 'hashottuborspa', 'poolcnt', 'pooltypeid10', 'pooltypeid2', 'pooltypeid7', 'storytypeid', 'fireplaceflag', 'taxdelinquencyflag']
We exclude: 9

In [31]:
del num_rows, missing_perc_thresh
gc.collect();

In [32]:
print ("Define training features ...")
exclude_other = ['parcelid', 'logerror', 'propertyzoningdesc']
train_features = []
for c in train_df.columns:
    if c not in exclude_missing \
       and c not in exclude_other:
        train_features.append(c)
print(train_features)
print("We use these for training: %s" % len(train_features))

Define training features ...
['transaction_year', 'transaction_month', 'transaction_day', 'transaction_quarter', 'airconditioningtypeid', 'bathroomcnt', 'bedroomcnt', 'buildingqualitytypeid', 'calculatedbathnbr', 'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet', 'finishedsquarefeet12', 'finishedsquarefeet15', 'finishedsquarefeet50', 'fips', 'fireplacecnt', 'fullbathcnt', 'garagecarcnt', 'garagetotalsqft', 'hashottuborspa', 'heatingorsystemtypeid', 'latitude', 'longitude', 'lotsizesquarefeet', 'poolcnt', 'pooltypeid7', 'propertycountylandusecode', 'propertylandusetypeid', 'rawcensustractandblock', 'regionidcity', 'regionidcounty', 'regionidneighborhood', 'regionidzip', 'roomcnt', 'threequarterbathnbr', 'unitcnt', 'yardbuildingsqft17', 'yearbuilt', 'numberofstories', 'structuretaxvaluedollarcnt', 'taxvaluedollarcnt', 'assessmentyear', 'landtaxvaluedollarcnt', 'taxamount', 'taxdelinquencyflag', 'taxdelinquencyyear', 'censustractandblock']
We use these for training: 47

<font color = blue> Now we have to deal with categorical features: </font>

In [33]:
print ("Define categorical features ...")
cat_feature_inds = []
cat_unique_thresh = 100
for i, c in enumerate(train_features):
    num_uniques = len(train_df[c].unique())
    if num_uniques < cat_unique_thresh \
       and not 'sqft' in c \
       and not 'cnt' in c \
       and not 'nbr' in c \
       and not 'number' in c:
        cat_feature_inds.append(i)
print("Cat features are: %s" % [train_features[ind] for ind in cat_feature_inds])

Define categorical features ...
Cat features are: ['transaction_year', 'transaction_month', 'transaction_day', 'transaction_quarter', 'airconditioningtypeid', 'buildingqualitytypeid', 'fips', 'hashottuborspa', 'heatingorsystemtypeid', 'pooltypeid7', 'propertycountylandusecode', 'propertylandusetypeid', 'regionidcounty', 'assessmentyear', 'taxdelinquencyflag', 'taxdelinquencyyear']

<font color = blue> As we are going to use a tree based model, we will replace NaN values by '-999' so they do not interfere with proper data: </font>

In [34]:
print ("Replacing NaN values by -999 ...")
train_df.fillna(-999, inplace=True)
test_df.fillna(-999, inplace=True)

Replacing NaN values by -999 ...

In [35]:
print ("Training model 2: Cat boost ...")
X_train = train_df[train_features]
y_train = train_df.logerror
print(X_train.shape, y_train.shape)

test_df['transactiondate'] = pd.Timestamp('2016-12-01') 
test_df = add_date_features(test_df)
X_test = test_df[train_features]
print(X_test.shape)

Training model 2: Cat boost ...
(167888, 47) (167888,)
(2985217, 47)

In [36]:
y_pred = 0.0
model = CatBoostRegressor(
    iterations = 630, learning_rate = 0.02,
    depth = 6, l2_leaf_reg = 3,
    loss_function = 'MAE',
    eval_metric = 'MAE',
    random_seed = i)
model.fit(
    X_train, y_train,
    cat_features = cat_feature_inds)
y_pred += model.predict(X_test)

0:	learn: 0.0690033	total: 364ms	remaining: 3m 48s
1:	learn: 0.0688482	total: 896ms	remaining: 4m 41s
2:	learn: 0.0687358	total: 1.28s	remaining: 4m 28s
3:	learn: 0.0686621	total: 1.55s	remaining: 4m 2s
4:	learn: 0.0686184	total: 1.84s	remaining: 3m 50s
5:	learn: 0.0685601	total: 2.2s	remaining: 3m 49s
6:	learn: 0.0685266	total: 2.55s	remaining: 3m 47s
7:	learn: 0.0684977	total: 2.92s	remaining: 3m 46s
8:	learn: 0.0684712	total: 3.71s	remaining: 4m 16s
9:	learn: 0.0684501	total: 4.05s	remaining: 4m 11s
10:	learn: 0.0684228	total: 4.37s	remaining: 4m 5s
11:	learn: 0.0684055	total: 4.71s	remaining: 4m 2s
12:	learn: 0.0683844	total: 4.98s	remaining: 3m 56s
13:	learn: 0.0683704	total: 5.26s	remaining: 3m 51s
14:	learn: 0.0683491	total: 5.56s	remaining: 3m 47s
15:	learn: 0.0683326	total: 5.84s	remaining: 3m 44s
16:	learn: 0.0683186	total: 6.15s	remaining: 3m 41s
17:	learn: 0.0683014	total: 6.42s	remaining: 3m 38s
18:	learn: 0.0682924	total: 6.68s	remaining: 3m 34s
19:	learn: 0.0682823	total: 6.95s	remaining: 3m 31s
20:	learn: 0.0682653	total: 7.23s	remaining: 3m 29s
21:	learn: 0.0682542	total: 7.55s	remaining: 3m 28s
22:	learn: 0.0682352	total: 7.83s	remaining: 3m 26s
23:	learn: 0.0682262	total: 8.09s	remaining: 3m 24s
24:	learn: 0.0682148	total: 8.37s	remaining: 3m 22s
25:	learn: 0.0682052	total: 8.68s	remaining: 3m 21s
26:	learn: 0.0681968	total: 8.94s	remaining: 3m 19s
27:	learn: 0.0681852	total: 9.22s	remaining: 3m 18s
28:	learn: 0.0681737	total: 9.49s	remaining: 3m 16s
29:	learn: 0.0681554	total: 9.76s	remaining: 3m 15s
30:	learn: 0.0681472	total: 10s	remaining: 3m 14s
31:	learn: 0.0681385	total: 10.3s	remaining: 3m 12s
32:	learn: 0.0681289	total: 10.6s	remaining: 3m 11s
33:	learn: 0.0681240	total: 10.8s	remaining: 3m 9s
34:	learn: 0.0681179	total: 11.1s	remaining: 3m 8s
35:	learn: 0.0681058	total: 11.4s	remaining: 3m 7s
36:	learn: 0.0680968	total: 11.7s	remaining: 3m 7s
37:	learn: 0.0680929	total: 12s	remaining: 3m 6s
38:	learn: 0.0680867	total: 12.3s	remaining: 3m 5s
39:	learn: 0.0680805	total: 12.6s	remaining: 3m 5s
40:	learn: 0.0680757	total: 12.9s	remaining: 3m 5s
41:	learn: 0.0680674	total: 13.3s	remaining: 3m 5s
42:	learn: 0.0680604	total: 14.2s	remaining: 3m 13s
43:	learn: 0.0680540	total: 14.5s	remaining: 3m 12s
44:	learn: 0.0680491	total: 14.8s	remaining: 3m 12s
45:	learn: 0.0680444	total: 15.1s	remaining: 3m 12s
46:	learn: 0.0680424	total: 15.6s	remaining: 3m 13s
47:	learn: 0.0680351	total: 15.8s	remaining: 3m 12s
48:	learn: 0.0680334	total: 16.1s	remaining: 3m 10s
49:	learn: 0.0680276	total: 16.4s	remaining: 3m 10s
50:	learn: 0.0680195	total: 16.7s	remaining: 3m 9s
51:	learn: 0.0680112	total: 16.9s	remaining: 3m 7s
52:	learn: 0.0680064	total: 17.2s	remaining: 3m 7s
53:	learn: 0.0680025	total: 17.4s	remaining: 3m 6s
54:	learn: 0.0680013	total: 17.8s	remaining: 3m 6s
55:	learn: 0.0679987	total: 18s	remaining: 3m 4s
56:	learn: 0.0679926	total: 18.4s	remaining: 3m 4s
57:	learn: 0.0679896	total: 18.7s	remaining: 3m 4s
58:	learn: 0.0679857	total: 18.9s	remaining: 3m 3s
59:	learn: 0.0679827	total: 19.2s	remaining: 3m 2s
60:	learn: 0.0679737	total: 19.5s	remaining: 3m 1s
61:	learn: 0.0679715	total: 19.7s	remaining: 3m
62:	learn: 0.0679701	total: 20s	remaining: 3m
63:	learn: 0.0679601	total: 20.3s	remaining: 2m 59s
64:	learn: 0.0679570	total: 20.6s	remaining: 2m 58s
65:	learn: 0.0679536	total: 20.8s	remaining: 2m 57s
66:	learn: 0.0679476	total: 21.1s	remaining: 2m 57s
67:	learn: 0.0679445	total: 21.4s	remaining: 2m 56s
68:	learn: 0.0679415	total: 21.7s	remaining: 2m 56s
69:	learn: 0.0679387	total: 21.9s	remaining: 2m 55s
70:	learn: 0.0679356	total: 22.2s	remaining: 2m 54s
71:	learn: 0.0679340	total: 22.5s	remaining: 2m 54s
72:	learn: 0.0679312	total: 22.8s	remaining: 2m 53s
73:	learn: 0.0679271	total: 23.1s	remaining: 2m 53s
74:	learn: 0.0679241	total: 23.5s	remaining: 2m 53s
75:	learn: 0.0679166	total: 23.8s	remaining: 2m 53s
76:	learn: 0.0679126	total: 24.7s	remaining: 2m 57s
77:	learn: 0.0679084	total: 25.1s	remaining: 2m 57s
78:	learn: 0.0679026	total: 25.3s	remaining: 2m 56s
79:	learn: 0.0678983	total: 25.6s	remaining: 2m 56s
80:	learn: 0.0678976	total: 25.9s	remaining: 2m 55s
81:	learn: 0.0678944	total: 26.1s	remaining: 2m 54s
82:	learn: 0.0678907	total: 26.4s	remaining: 2m 53s
83:	learn: 0.0678862	total: 26.7s	remaining: 2m 53s
84:	learn: 0.0678824	total: 27s	remaining: 2m 52s
85:	learn: 0.0678802	total: 27.2s	remaining: 2m 52s
86:	learn: 0.0678766	total: 27.5s	remaining: 2m 51s
87:	learn: 0.0678751	total: 27.8s	remaining: 2m 50s
88:	learn: 0.0678714	total: 28s	remaining: 2m 50s
89:	learn: 0.0678651	total: 28.3s	remaining: 2m 49s
90:	learn: 0.0678594	total: 28.6s	remaining: 2m 49s
91:	learn: 0.0678551	total: 28.8s	remaining: 2m 48s
92:	learn: 0.0678528	total: 29.1s	remaining: 2m 48s
93:	learn: 0.0678486	total: 29.4s	remaining: 2m 47s
94:	learn: 0.0678466	total: 29.7s	remaining: 2m 47s
95:	learn: 0.0678440	total: 30s	remaining: 2m 46s
96:	learn: 0.0678418	total: 30.3s	remaining: 2m 46s
97:	learn: 0.0678396	total: 30.6s	remaining: 2m 46s
98:	learn: 0.0678381	total: 30.9s	remaining: 2m 45s
99:	learn: 0.0678358	total: 31.1s	remaining: 2m 45s
100:	learn: 0.0678352	total: 31.3s	remaining: 2m 43s
101:	learn: 0.0678331	total: 31.5s	remaining: 2m 43s
102:	learn: 0.0678301	total: 31.8s	remaining: 2m 42s
103:	learn: 0.0678291	total: 32.1s	remaining: 2m 42s
104:	learn: 0.0678252	total: 32.4s	remaining: 2m 41s
105:	learn: 0.0678235	total: 32.6s	remaining: 2m 41s
106:	learn: 0.0678225	total: 32.9s	remaining: 2m 40s
107:	learn: 0.0678206	total: 33.3s	remaining: 2m 41s
108:	learn: 0.0678157	total: 33.7s	remaining: 2m 41s
109:	learn: 0.0678136	total: 34.1s	remaining: 2m 41s
110:	learn: 0.0678121	total: 35.1s	remaining: 2m 44s
111:	learn: 0.0678089	total: 35.5s	remaining: 2m 44s
112:	learn: 0.0678023	total: 35.7s	remaining: 2m 43s
113:	learn: 0.0677983	total: 36s	remaining: 2m 42s
114:	learn: 0.0677938	total: 36.3s	remaining: 2m 42s
115:	learn: 0.0677924	total: 36.6s	remaining: 2m 41s
116:	learn: 0.0677912	total: 36.9s	remaining: 2m 41s
117:	learn: 0.0677892	total: 37.1s	remaining: 2m 41s
118:	learn: 0.0677873	total: 37.4s	remaining: 2m 40s
119:	learn: 0.0677842	total: 37.7s	remaining: 2m 40s
120:	learn: 0.0677813	total: 38s	remaining: 2m 39s
121:	learn: 0.0677806	total: 38.2s	remaining: 2m 39s
122:	learn: 0.0677780	total: 38.5s	remaining: 2m 38s
123:	learn: 0.0677768	total: 38.7s	remaining: 2m 38s
124:	learn: 0.0677753	total: 39s	remaining: 2m 37s
125:	learn: 0.0677741	total: 39.3s	remaining: 2m 37s
126:	learn: 0.0677722	total: 39.6s	remaining: 2m 36s
127:	learn: 0.0677703	total: 39.8s	remaining: 2m 36s
128:	learn: 0.0677692	total: 40.1s	remaining: 2m 35s
129:	learn: 0.0677689	total: 40.3s	remaining: 2m 35s
130:	learn: 0.0677660	total: 40.6s	remaining: 2m 34s
131:	learn: 0.0677611	total: 40.9s	remaining: 2m 34s
132:	learn: 0.0677572	total: 41.2s	remaining: 2m 33s
133:	learn: 0.0677567	total: 41.5s	remaining: 2m 33s
134:	learn: 0.0677548	total: 41.7s	remaining: 2m 33s
135:	learn: 0.0677522	total: 42s	remaining: 2m 32s
136:	learn: 0.0677511	total: 42.3s	remaining: 2m 32s
137:	learn: 0.0677494	total: 42.5s	remaining: 2m 31s
138:	learn: 0.0677465	total: 42.9s	remaining: 2m 31s
139:	learn: 0.0677446	total: 43.3s	remaining: 2m 31s
140:	learn: 0.0677422	total: 43.7s	remaining: 2m 31s
141:	learn: 0.0677387	total: 44.1s	remaining: 2m 31s
142:	learn: 0.0677365	total: 44.5s	remaining: 2m 31s
143:	learn: 0.0677344	total: 45.5s	remaining: 2m 33s
144:	learn: 0.0677307	total: 45.8s	remaining: 2m 33s
145:	learn: 0.0677281	total: 46.1s	remaining: 2m 32s
146:	learn: 0.0677243	total: 46.4s	remaining: 2m 32s
147:	learn: 0.0677232	total: 46.6s	remaining: 2m 31s
148:	learn: 0.0677200	total: 46.9s	remaining: 2m 31s
149:	learn: 0.0677186	total: 47.2s	remaining: 2m 31s
150:	learn: 0.0677167	total: 47.5s	remaining: 2m 30s
151:	learn: 0.0677134	total: 47.8s	remaining: 2m 30s
152:	learn: 0.0677104	total: 48.1s	remaining: 2m 29s
153:	learn: 0.0677080	total: 48.3s	remaining: 2m 29s
154:	learn: 0.0677069	total: 48.5s	remaining: 2m 28s
155:	learn: 0.0677055	total: 48.8s	remaining: 2m 28s
156:	learn: 0.0677042	total: 49s	remaining: 2m 27s
157:	learn: 0.0677034	total: 49.3s	remaining: 2m 27s

158:	learn: 0.0677023	total: 49.6s	remaining: 2m 26s
159:	learn: 0.0677023	total: 49.6s	remaining: 2m 25s
160:	learn: 0.0677018	total: 49.9s	remaining: 2m 25s
161:	learn: 0.0677003	total: 50.1s	remaining: 2m 24s
162:	learn: 0.0676998	total: 50.3s	remaining: 2m 24s
163:	learn: 0.0676965	total: 50.6s	remaining: 2m 23s
164:	learn: 0.0676952	total: 50.9s	remaining: 2m 23s
165:	learn: 0.0676930	total: 51.2s	remaining: 2m 23s
166:	learn: 0.0676896	total: 51.4s	remaining: 2m 22s
167:	learn: 0.0676873	total: 51.6s	remaining: 2m 22s
168:	learn: 0.0676862	total: 51.9s	remaining: 2m 21s
169:	learn: 0.0676851	total: 52.1s	remaining: 2m 21s
170:	learn: 0.0676803	total: 52.4s	remaining: 2m 20s
171:	learn: 0.0676800	total: 52.6s	remaining: 2m 20s
172:	learn: 0.0676770	total: 52.9s	remaining: 2m 19s
173:	learn: 0.0676762	total: 53.2s	remaining: 2m 19s
174:	learn: 0.0676741	total: 53.5s	remaining: 2m 19s
175:	learn: 0.0676721	total: 53.9s	remaining: 2m 18s
176:	learn: 0.0676703	total: 54.3s	remaining: 2m 18s
177:	learn: 0.0676687	total: 54.7s	remaining: 2m 18s
178:	learn: 0.0676680	total: 55.6s	remaining: 2m 20s
179:	learn: 0.0676661	total: 55.9s	remaining: 2m 19s
180:	learn: 0.0676645	total: 56.2s	remaining: 2m 19s
181:	learn: 0.0676623	total: 56.5s	remaining: 2m 19s
182:	learn: 0.0676603	total: 56.8s	remaining: 2m 18s
183:	learn: 0.0676562	total: 57s	remaining: 2m 18s
184:	learn: 0.0676510	total: 57.3s	remaining: 2m 17s
185:	learn: 0.0676491	total: 57.6s	remaining: 2m 17s
186:	learn: 0.0676451	total: 57.9s	remaining: 2m 17s
187:	learn: 0.0676434	total: 58.1s	remaining: 2m 16s
188:	learn: 0.0676410	total: 58.4s	remaining: 2m 16s
189:	learn: 0.0676393	total: 58.6s	remaining: 2m 15s
190:	learn: 0.0676382	total: 58.9s	remaining: 2m 15s
191:	learn: 0.0676346	total: 59.2s	remaining: 2m 15s
192:	learn: 0.0676335	total: 59.4s	remaining: 2m 14s
193:	learn: 0.0676326	total: 59.7s	remaining: 2m 14s
194:	learn: 0.0676315	total: 59.9s	remaining: 2m 13s
195:	learn: 0.0676294	total: 1m	remaining: 2m 13s
196:	learn: 0.0676286	total: 1m	remaining: 2m 12s
197:	learn: 0.0676265	total: 1m	remaining: 2m 12s
198:	learn: 0.0676255	total: 1m	remaining: 2m 11s
199:	learn: 0.0676236	total: 1m 1s	remaining: 2m 11s
200:	learn: 0.0676209	total: 1m 1s	remaining: 2m 11s
201:	learn: 0.0676197	total: 1m 1s	remaining: 2m 10s
202:	learn: 0.0676187	total: 1m 1s	remaining: 2m 10s
203:	learn: 0.0676135	total: 1m 2s	remaining: 2m 9s
204:	learn: 0.0676117	total: 1m 2s	remaining: 2m 9s
205:	learn: 0.0676111	total: 1m 2s	remaining: 2m 9s
206:	learn: 0.0676092	total: 1m 2s	remaining: 2m 8s
207:	learn: 0.0676081	total: 1m 3s	remaining: 2m 8s
208:	learn: 0.0676063	total: 1m 3s	remaining: 2m 7s
209:	learn: 0.0676057	total: 1m 3s	remaining: 2m 7s
210:	learn: 0.0676035	total: 1m 4s	remaining: 2m 7s
211:	learn: 0.0676024	total: 1m 4s	remaining: 2m 6s
212:	learn: 0.0676002	total: 1m 4s	remaining: 2m 6s
213:	learn: 0.0675975	total: 1m 5s	remaining: 2m 6s
214:	learn: 0.0675950	total: 1m 5s	remaining: 2m 7s
215:	learn: 0.0675944	total: 1m 6s	remaining: 2m 6s
216:	learn: 0.0675935	total: 1m 6s	remaining: 2m 6s
217:	learn: 0.0675901	total: 1m 6s	remaining: 2m 6s
218:	learn: 0.0675887	total: 1m 7s	remaining: 2m 5s
219:	learn: 0.0675864	total: 1m 7s	remaining: 2m 5s
220:	learn: 0.0675836	total: 1m 7s	remaining: 2m 5s
221:	learn: 0.0675816	total: 1m 7s	remaining: 2m 4s
222:	learn: 0.0675768	total: 1m 8s	remaining: 2m 4s
223:	learn: 0.0675752	total: 1m 8s	remaining: 2m 3s
224:	learn: 0.0675743	total: 1m 8s	remaining: 2m 3s
225:	learn: 0.0675734	total: 1m 8s	remaining: 2m 3s
226:	learn: 0.0675713	total: 1m 9s	remaining: 2m 2s
227:	learn: 0.0675668	total: 1m 9s	remaining: 2m 2s
228:	learn: 0.0675652	total: 1m 9s	remaining: 2m 2s
229:	learn: 0.0675593	total: 1m 9s	remaining: 2m 1s
230:	learn: 0.0675583	total: 1m 10s	remaining: 2m 1s
231:	learn: 0.0675544	total: 1m 10s	remaining: 2m
232:	learn: 0.0675514	total: 1m 10s	remaining: 2m
233:	learn: 0.0675480	total: 1m 10s	remaining: 2m
234:	learn: 0.0675459	total: 1m 11s	remaining: 1m 59s
235:	learn: 0.0675449	total: 1m 11s	remaining: 1m 59s
236:	learn: 0.0675440	total: 1m 11s	remaining: 1m 59s
237:	learn: 0.0675408	total: 1m 12s	remaining: 1m 58s
238:	learn: 0.0675402	total: 1m 12s	remaining: 1m 58s
239:	learn: 0.0675401	total: 1m 12s	remaining: 1m 57s
240:	learn: 0.0675390	total: 1m 12s	remaining: 1m 57s
241:	learn: 0.0675367	total: 1m 12s	remaining: 1m 56s
242:	learn: 0.0675348	total: 1m 13s	remaining: 1m 56s
243:	learn: 0.0675336	total: 1m 13s	remaining: 1m 56s
244:	learn: 0.0675310	total: 1m 13s	remaining: 1m 55s
245:	learn: 0.0675305	total: 1m 13s	remaining: 1m 55s
246:	learn: 0.0675275	total: 1m 14s	remaining: 1m 55s
247:	learn: 0.0675253	total: 1m 14s	remaining: 1m 54s
248:	learn: 0.0675230	total: 1m 14s	remaining: 1m 54s
249:	learn: 0.0675205	total: 1m 15s	remaining: 1m 54s
250:	learn: 0.0675193	total: 1m 15s	remaining: 1m 54s
251:	learn: 0.0675179	total: 1m 16s	remaining: 1m 54s
252:	learn: 0.0675164	total: 1m 16s	remaining: 1m 54s
253:	learn: 0.0675146	total: 1m 16s	remaining: 1m 53s
254:	learn: 0.0675135	total: 1m 17s	remaining: 1m 53s
255:	learn: 0.0675129	total: 1m 17s	remaining: 1m 53s
256:	learn: 0.0675129	total: 1m 17s	remaining: 1m 52s
257:	learn: 0.0675124	total: 1m 17s	remaining: 1m 52s
258:	learn: 0.0675120	total: 1m 18s	remaining: 1m 51s
259:	learn: 0.0675102	total: 1m 18s	remaining: 1m 51s
260:	learn: 0.0675092	total: 1m 18s	remaining: 1m 51s
261:	learn: 0.0675081	total: 1m 18s	remaining: 1m 50s
262:	learn: 0.0675081	total: 1m 18s	remaining: 1m 50s
263:	learn: 0.0675067	total: 1m 19s	remaining: 1m 49s
264:	learn: 0.0675016	total: 1m 19s	remaining: 1m 49s
265:	learn: 0.0674991	total: 1m 19s	remaining: 1m 49s
266:	learn: 0.0674957	total: 1m 20s	remaining: 1m 48s
267:	learn: 0.0674951	total: 1m 20s	remaining: 1m 48s
268:	learn: 0.0674941	total: 1m 20s	remaining: 1m 48s
269:	learn: 0.0674923	total: 1m 20s	remaining: 1m 47s
270:	learn: 0.0674909	total: 1m 21s	remaining: 1m 47s
271:	learn: 0.0674894	total: 1m 21s	remaining: 1m 46s
272:	learn: 0.0674877	total: 1m 21s	remaining: 1m 46s
273:	learn: 0.0674875	total: 1m 21s	remaining: 1m 46s
274:	learn: 0.0674855	total: 1m 21s	remaining: 1m 45s
275:	learn: 0.0674849	total: 1m 22s	remaining: 1m 45s
276:	learn: 0.0674837	total: 1m 22s	remaining: 1m 45s
277:	learn: 0.0674821	total: 1m 22s	remaining: 1m 44s
278:	learn: 0.0674803	total: 1m 23s	remaining: 1m 44s
279:	learn: 0.0674781	total: 1m 23s	remaining: 1m 44s
280:	learn: 0.0674727	total: 1m 23s	remaining: 1m 43s
281:	learn: 0.0674697	total: 1m 23s	remaining: 1m 43s
282:	learn: 0.0674668	total: 1m 24s	remaining: 1m 43s
283:	learn: 0.0674649	total: 1m 24s	remaining: 1m 42s
284:	learn: 0.0674647	total: 1m 24s	remaining: 1m 42s
285:	learn: 0.0674629	total: 1m 25s	remaining: 1m 42s
286:	learn: 0.0674618	total: 1m 25s	remaining: 1m 42s
287:	learn: 0.0674610	total: 1m 25s	remaining: 1m 41s
288:	learn: 0.0674595	total: 1m 26s	remaining: 1m 41s
289:	learn: 0.0674587	total: 1m 26s	remaining: 1m 41s
290:	learn: 0.0674556	total: 1m 27s	remaining: 1m 41s
291:	learn: 0.0674526	total: 1m 27s	remaining: 1m 41s
292:	learn: 0.0674500	total: 1m 27s	remaining: 1m 40s
293:	learn: 0.0674492	total: 1m 28s	remaining: 1m 40s
294:	learn: 0.0674478	total: 1m 28s	remaining: 1m 40s
295:	learn: 0.0674465	total: 1m 28s	remaining: 1m 39s
296:	learn: 0.0674442	total: 1m 28s	remaining: 1m 39s
297:	learn: 0.0674424	total: 1m 29s	remaining: 1m 39s
298:	learn: 0.0674419	total: 1m 29s	remaining: 1m 38s
299:	learn: 0.0674404	total: 1m 29s	remaining: 1m 38s
300:	learn: 0.0674390	total: 1m 29s	remaining: 1m 38s
301:	learn: 0.0674365	total: 1m 30s	remaining: 1m 37s
302:	learn: 0.0674350	total: 1m 30s	remaining: 1m 37s
303:	learn: 0.0674338	total: 1m 30s	remaining: 1m 37s
304:	learn: 0.0674333	total: 1m 30s	remaining: 1m 36s
305:	learn: 0.0674322	total: 1m 31s	remaining: 1m 36s
306:	learn: 0.0674317	total: 1m 31s	remaining: 1m 36s
307:	learn: 0.0674307	total: 1m 31s	remaining: 1m 35s
308:	learn: 0.0674288	total: 1m 31s	remaining: 1m 35s
309:	learn: 0.0674270	total: 1m 32s	remaining: 1m 35s
310:	learn: 0.0674255	total: 1m 32s	remaining: 1m 34s
311:	learn: 0.0674218	total: 1m 32s	remaining: 1m 34s
312:	learn: 0.0674203	total: 1m 32s	remaining: 1m 34s

313:	learn: 0.0674193	total: 1m 33s	remaining: 1m 33s
314:	learn: 0.0674190	total: 1m 33s	remaining: 1m 33s
315:	learn: 0.0674178	total: 1m 33s	remaining: 1m 33s
316:	learn: 0.0674161	total: 1m 33s	remaining: 1m 32s
317:	learn: 0.0674149	total: 1m 34s	remaining: 1m 32s
318:	learn: 0.0674133	total: 1m 34s	remaining: 1m 32s
319:	learn: 0.0674122	total: 1m 34s	remaining: 1m 31s
320:	learn: 0.0674121	total: 1m 34s	remaining: 1m 31s
321:	learn: 0.0674118	total: 1m 35s	remaining: 1m 30s
322:	learn: 0.0674113	total: 1m 35s	remaining: 1m 30s
323:	learn: 0.0674100	total: 1m 35s	remaining: 1m 30s
324:	learn: 0.0674089	total: 1m 36s	remaining: 1m 30s
325:	learn: 0.0674082	total: 1m 36s	remaining: 1m 30s
326:	learn: 0.0674076	total: 1m 37s	remaining: 1m 30s
327:	learn: 0.0674060	total: 1m 37s	remaining: 1m 29s
328:	learn: 0.0674060	total: 1m 37s	remaining: 1m 29s
329:	learn: 0.0674033	total: 1m 37s	remaining: 1m 29s
330:	learn: 0.0674014	total: 1m 38s	remaining: 1m 28s
331:	learn: 0.0673994	total: 1m 38s	remaining: 1m 28s
332:	learn: 0.0673981	total: 1m 38s	remaining: 1m 28s
333:	learn: 0.0673969	total: 1m 38s	remaining: 1m 27s
334:	learn: 0.0673959	total: 1m 39s	remaining: 1m 27s
335:	learn: 0.0673908	total: 1m 39s	remaining: 1m 27s
336:	learn: 0.0673897	total: 1m 39s	remaining: 1m 26s
337:	learn: 0.0673889	total: 1m 39s	remaining: 1m 26s
338:	learn: 0.0673852	total: 1m 40s	remaining: 1m 26s
339:	learn: 0.0673842	total: 1m 40s	remaining: 1m 25s
340:	learn: 0.0673835	total: 1m 40s	remaining: 1m 25s
341:	learn: 0.0673830	total: 1m 40s	remaining: 1m 24s
342:	learn: 0.0673816	total: 1m 41s	remaining: 1m 24s
343:	learn: 0.0673794	total: 1m 41s	remaining: 1m 24s
344:	learn: 0.0673767	total: 1m 41s	remaining: 1m 24s
345:	learn: 0.0673761	total: 1m 41s	remaining: 1m 23s
346:	learn: 0.0673756	total: 1m 42s	remaining: 1m 23s
347:	learn: 0.0673750	total: 1m 42s	remaining: 1m 23s
348:	learn: 0.0673747	total: 1m 42s	remaining: 1m 22s
349:	learn: 0.0673739	total: 1m 42s	remaining: 1m 22s
350:	learn: 0.0673739	total: 1m 43s	remaining: 1m 21s
351:	learn: 0.0673735	total: 1m 43s	remaining: 1m 21s
352:	learn: 0.0673732	total: 1m 43s	remaining: 1m 21s
353:	learn: 0.0673720	total: 1m 43s	remaining: 1m 20s
354:	learn: 0.0673701	total: 1m 44s	remaining: 1m 20s
355:	learn: 0.0673700	total: 1m 44s	remaining: 1m 20s
356:	learn: 0.0673695	total: 1m 44s	remaining: 1m 19s
357:	learn: 0.0673694	total: 1m 44s	remaining: 1m 19s
358:	learn: 0.0673685	total: 1m 44s	remaining: 1m 19s
359:	learn: 0.0673662	total: 1m 45s	remaining: 1m 18s
360:	learn: 0.0673656	total: 1m 45s	remaining: 1m 18s
361:	learn: 0.0673651	total: 1m 45s	remaining: 1m 18s
362:	learn: 0.0673629	total: 1m 45s	remaining: 1m 17s
363:	learn: 0.0673599	total: 1m 46s	remaining: 1m 17s
364:	learn: 0.0673566	total: 1m 47s	remaining: 1m 17s
365:	learn: 0.0673562	total: 1m 47s	remaining: 1m 17s
366:	learn: 0.0673545	total: 1m 47s	remaining: 1m 17s
367:	learn: 0.0673536	total: 1m 48s	remaining: 1m 16s
368:	learn: 0.0673533	total: 1m 48s	remaining: 1m 16s
369:	learn: 0.0673525	total: 1m 48s	remaining: 1m 16s
370:	learn: 0.0673513	total: 1m 48s	remaining: 1m 15s
371:	learn: 0.0673482	total: 1m 49s	remaining: 1m 15s
372:	learn: 0.0673479	total: 1m 49s	remaining: 1m 15s
373:	learn: 0.0673470	total: 1m 49s	remaining: 1m 15s
374:	learn: 0.0673429	total: 1m 49s	remaining: 1m 14s
375:	learn: 0.0673421	total: 1m 50s	remaining: 1m 14s
376:	learn: 0.0673404	total: 1m 50s	remaining: 1m 14s
377:	learn: 0.0673400	total: 1m 50s	remaining: 1m 13s
378:	learn: 0.0673392	total: 1m 50s	remaining: 1m 13s
379:	learn: 0.0673378	total: 1m 51s	remaining: 1m 13s
380:	learn: 0.0673357	total: 1m 51s	remaining: 1m 12s
381:	learn: 0.0673351	total: 1m 51s	remaining: 1m 12s
382:	learn: 0.0673346	total: 1m 51s	remaining: 1m 12s
383:	learn: 0.0673316	total: 1m 52s	remaining: 1m 11s
384:	learn: 0.0673301	total: 1m 52s	remaining: 1m 11s
385:	learn: 0.0673295	total: 1m 52s	remaining: 1m 11s
386:	learn: 0.0673282	total: 1m 52s	remaining: 1m 10s
387:	learn: 0.0673266	total: 1m 53s	remaining: 1m 10s
388:	learn: 0.0673264	total: 1m 53s	remaining: 1m 10s
389:	learn: 0.0673252	total: 1m 53s	remaining: 1m 9s
390:	learn: 0.0673223	total: 1m 53s	remaining: 1m 9s
391:	learn: 0.0673216	total: 1m 54s	remaining: 1m 9s
392:	learn: 0.0673216	total: 1m 54s	remaining: 1m 8s
393:	learn: 0.0673193	total: 1m 54s	remaining: 1m 8s
394:	learn: 0.0673174	total: 1m 54s	remaining: 1m 8s
395:	learn: 0.0673167	total: 1m 54s	remaining: 1m 7s
396:	learn: 0.0673162	total: 1m 55s	remaining: 1m 7s
397:	learn: 0.0673155	total: 1m 55s	remaining: 1m 7s
398:	learn: 0.0673153	total: 1m 55s	remaining: 1m 6s
399:	learn: 0.0673122	total: 1m 55s	remaining: 1m 6s
400:	learn: 0.0673103	total: 1m 56s	remaining: 1m 6s
401:	learn: 0.0673084	total: 1m 56s	remaining: 1m 6s
402:	learn: 0.0673063	total: 1m 56s	remaining: 1m 5s
403:	learn: 0.0673058	total: 1m 57s	remaining: 1m 5s
404:	learn: 0.0673048	total: 1m 58s	remaining: 1m 5s
405:	learn: 0.0673036	total: 1m 58s	remaining: 1m 5s
406:	learn: 0.0673026	total: 1m 58s	remaining: 1m 4s
407:	learn: 0.0673023	total: 1m 58s	remaining: 1m 4s
408:	learn: 0.0673023	total: 1m 58s	remaining: 1m 4s
409:	learn: 0.0673005	total: 1m 59s	remaining: 1m 3s
410:	learn: 0.0673000	total: 1m 59s	remaining: 1m 3s
411:	learn: 0.0672996	total: 1m 59s	remaining: 1m 3s
412:	learn: 0.0672993	total: 1m 59s	remaining: 1m 3s
413:	learn: 0.0672987	total: 2m	remaining: 1m 2s
414:	learn: 0.0672961	total: 2m	remaining: 1m 2s
415:	learn: 0.0672954	total: 2m	remaining: 1m 2s
416:	learn: 0.0672942	total: 2m 1s	remaining: 1m 1s
417:	learn: 0.0672921	total: 2m 1s	remaining: 1m 1s
418:	learn: 0.0672916	total: 2m 1s	remaining: 1m 1s
419:	learn: 0.0672904	total: 2m 1s	remaining: 1m
420:	learn: 0.0672898	total: 2m 1s	remaining: 1m
421:	learn: 0.0672879	total: 2m 2s	remaining: 1m
422:	learn: 0.0672877	total: 2m 2s	remaining: 59.9s
423:	learn: 0.0672863	total: 2m 2s	remaining: 59.6s
424:	learn: 0.0672857	total: 2m 2s	remaining: 59.3s
425:	learn: 0.0672853	total: 2m 3s	remaining: 59s
426:	learn: 0.0672835	total: 2m 3s	remaining: 58.7s
427:	learn: 0.0672826	total: 2m 3s	remaining: 58.4s
428:	learn: 0.0672826	total: 2m 3s	remaining: 58s
429:	learn: 0.0672804	total: 2m 4s	remaining: 57.7s
430:	learn: 0.0672784	total: 2m 4s	remaining: 57.4s
431:	learn: 0.0672772	total: 2m 4s	remaining: 57.1s
432:	learn: 0.0672757	total: 2m 4s	remaining: 56.8s
433:	learn: 0.0672751	total: 2m 5s	remaining: 56.5s
434:	learn: 0.0672730	total: 2m 5s	remaining: 56.2s
435:	learn: 0.0672698	total: 2m 5s	remaining: 55.9s
436:	learn: 0.0672694	total: 2m 5s	remaining: 55.6s
437:	learn: 0.0672673	total: 2m 6s	remaining: 55.3s
438:	learn: 0.0672666	total: 2m 6s	remaining: 55.1s
439:	learn: 0.0672655	total: 2m 6s	remaining: 54.8s
440:	learn: 0.0672643	total: 2m 7s	remaining: 54.5s
441:	learn: 0.0672639	total: 2m 8s	remaining: 54.5s
442:	learn: 0.0672606	total: 2m 8s	remaining: 54.2s
443:	learn: 0.0672597	total: 2m 8s	remaining: 53.9s
444:	learn: 0.0672582	total: 2m 8s	remaining: 53.6s
445:	learn: 0.0672569	total: 2m 9s	remaining: 53.3s
446:	learn: 0.0672555	total: 2m 9s	remaining: 53s
447:	learn: 0.0672546	total: 2m 9s	remaining: 52.7s
448:	learn: 0.0672543	total: 2m 10s	remaining: 52.4s
449:	learn: 0.0672537	total: 2m 10s	remaining: 52.1s
450:	learn: 0.0672526	total: 2m 10s	remaining: 51.8s
451:	learn: 0.0672498	total: 2m 10s	remaining: 51.5s
452:	learn: 0.0672494	total: 2m 11s	remaining: 51.2s
453:	learn: 0.0672487	total: 2m 11s	remaining: 50.9s
454:	learn: 0.0672483	total: 2m 11s	remaining: 50.6s
455:	learn: 0.0672471	total: 2m 11s	remaining: 50.3s
456:	learn: 0.0672466	total: 2m 12s	remaining: 50s
457:	learn: 0.0672443	total: 2m 12s	remaining: 49.7s
458:	learn: 0.0672435	total: 2m 12s	remaining: 49.4s
459:	learn: 0.0672429	total: 2m 12s	remaining: 49.1s
460:	learn: 0.0672422	total: 2m 13s	remaining: 48.8s
461:	learn: 0.0672405	total: 2m 13s	remaining: 48.5s
462:	learn: 0.0672402	total: 2m 13s	remaining: 48.2s
463:	learn: 0.0672397	total: 2m 13s	remaining: 47.9s
464:	learn: 0.0672385	total: 2m 14s	remaining: 47.6s
465:	learn: 0.0672378	total: 2m 14s	remaining: 47.3s
466:	learn: 0.0672364	total: 2m 14s	remaining: 47s
467:	learn: 0.0672351	total: 2m 14s	remaining: 46.7s

468:	learn: 0.0672344	total: 2m 15s	remaining: 46.4s
469:	learn: 0.0672330	total: 2m 15s	remaining: 46.1s
470:	learn: 0.0672324	total: 2m 15s	remaining: 45.8s
471:	learn: 0.0672319	total: 2m 15s	remaining: 45.5s
472:	learn: 0.0672312	total: 2m 16s	remaining: 45.2s
473:	learn: 0.0672304	total: 2m 16s	remaining: 44.9s
474:	learn: 0.0672291	total: 2m 16s	remaining: 44.6s
475:	learn: 0.0672275	total: 2m 17s	remaining: 44.3s
476:	learn: 0.0672269	total: 2m 17s	remaining: 44s
477:	learn: 0.0672256	total: 2m 17s	remaining: 43.8s
478:	learn: 0.0672249	total: 2m 18s	remaining: 43.7s
479:	learn: 0.0672235	total: 2m 18s	remaining: 43.4s
480:	learn: 0.0672222	total: 2m 19s	remaining: 43.1s
481:	learn: 0.0672218	total: 2m 19s	remaining: 42.8s
482:	learn: 0.0672217	total: 2m 19s	remaining: 42.5s
483:	learn: 0.0672214	total: 2m 19s	remaining: 42.1s
484:	learn: 0.0672198	total: 2m 19s	remaining: 41.8s
485:	learn: 0.0672180	total: 2m 20s	remaining: 41.6s
486:	learn: 0.0672152	total: 2m 20s	remaining: 41.3s
487:	learn: 0.0672130	total: 2m 20s	remaining: 41s
488:	learn: 0.0672119	total: 2m 21s	remaining: 40.7s
489:	learn: 0.0672112	total: 2m 21s	remaining: 40.4s
490:	learn: 0.0672086	total: 2m 21s	remaining: 40.1s
491:	learn: 0.0672081	total: 2m 21s	remaining: 39.8s
492:	learn: 0.0672052	total: 2m 22s	remaining: 39.5s
493:	learn: 0.0672050	total: 2m 22s	remaining: 39.2s
494:	learn: 0.0672021	total: 2m 22s	remaining: 38.9s
495:	learn: 0.0672012	total: 2m 22s	remaining: 38.6s
496:	learn: 0.0672005	total: 2m 23s	remaining: 38.3s
497:	learn: 0.0671997	total: 2m 23s	remaining: 38s
498:	learn: 0.0671971	total: 2m 23s	remaining: 37.7s
499:	learn: 0.0671958	total: 2m 23s	remaining: 37.4s
500:	learn: 0.0671952	total: 2m 24s	remaining: 37.1s
501:	learn: 0.0671935	total: 2m 24s	remaining: 36.8s
502:	learn: 0.0671920	total: 2m 24s	remaining: 36.5s
503:	learn: 0.0671915	total: 2m 24s	remaining: 36.2s
504:	learn: 0.0671904	total: 2m 25s	remaining: 35.9s
505:	learn: 0.0671873	total: 2m 25s	remaining: 35.6s
506:	learn: 0.0671863	total: 2m 25s	remaining: 35.3s
507:	learn: 0.0671857	total: 2m 25s	remaining: 35s
508:	learn: 0.0671824	total: 2m 26s	remaining: 34.7s
509:	learn: 0.0671821	total: 2m 26s	remaining: 34.5s
510:	learn: 0.0671804	total: 2m 26s	remaining: 34.2s
511:	learn: 0.0671803	total: 2m 26s	remaining: 33.9s
512:	learn: 0.0671792	total: 2m 27s	remaining: 33.6s
513:	learn: 0.0671774	total: 2m 27s	remaining: 33.3s
514:	learn: 0.0671763	total: 2m 27s	remaining: 33s
515:	learn: 0.0671733	total: 2m 28s	remaining: 32.9s
516:	learn: 0.0671733	total: 2m 28s	remaining: 32.5s
517:	learn: 0.0671727	total: 2m 29s	remaining: 32.2s
518:	learn: 0.0671721	total: 2m 29s	remaining: 32s
519:	learn: 0.0671721	total: 2m 29s	remaining: 31.6s
520:	learn: 0.0671719	total: 2m 29s	remaining: 31.3s
521:	learn: 0.0671709	total: 2m 30s	remaining: 31s
522:	learn: 0.0671685	total: 2m 30s	remaining: 30.8s
523:	learn: 0.0671668	total: 2m 30s	remaining: 30.5s
524:	learn: 0.0671655	total: 2m 30s	remaining: 30.2s
525:	learn: 0.0671642	total: 2m 31s	remaining: 29.9s
526:	learn: 0.0671629	total: 2m 31s	remaining: 29.6s
527:	learn: 0.0671618	total: 2m 31s	remaining: 29.3s
528:	learn: 0.0671602	total: 2m 31s	remaining: 29s
529:	learn: 0.0671602	total: 2m 32s	remaining: 28.7s
530:	learn: 0.0671582	total: 2m 32s	remaining: 28.4s
531:	learn: 0.0671556	total: 2m 32s	remaining: 28.1s
532:	learn: 0.0671543	total: 2m 32s	remaining: 27.8s
533:	learn: 0.0671531	total: 2m 33s	remaining: 27.5s
534:	learn: 0.0671518	total: 2m 33s	remaining: 27.2s
535:	learn: 0.0671493	total: 2m 33s	remaining: 27s
536:	learn: 0.0671490	total: 2m 33s	remaining: 26.7s
537:	learn: 0.0671482	total: 2m 34s	remaining: 26.4s
538:	learn: 0.0671467	total: 2m 34s	remaining: 26.1s
539:	learn: 0.0671444	total: 2m 34s	remaining: 25.8s
540:	learn: 0.0671406	total: 2m 35s	remaining: 25.5s
541:	learn: 0.0671386	total: 2m 35s	remaining: 25.2s
542:	learn: 0.0671357	total: 2m 35s	remaining: 24.9s
543:	learn: 0.0671347	total: 2m 35s	remaining: 24.6s
544:	learn: 0.0671313	total: 2m 36s	remaining: 24.3s
545:	learn: 0.0671307	total: 2m 36s	remaining: 24s
546:	learn: 0.0671302	total: 2m 36s	remaining: 23.8s
547:	learn: 0.0671293	total: 2m 36s	remaining: 23.5s
548:	learn: 0.0671279	total: 2m 37s	remaining: 23.2s
549:	learn: 0.0671267	total: 2m 37s	remaining: 22.9s
550:	learn: 0.0671256	total: 2m 37s	remaining: 22.6s
551:	learn: 0.0671247	total: 2m 38s	remaining: 22.3s
552:	learn: 0.0671232	total: 2m 39s	remaining: 22.1s
553:	learn: 0.0671205	total: 2m 39s	remaining: 21.9s
554:	learn: 0.0671171	total: 2m 39s	remaining: 21.6s
555:	learn: 0.0671157	total: 2m 39s	remaining: 21.3s
556:	learn: 0.0671147	total: 2m 40s	remaining: 21s
557:	learn: 0.0671139	total: 2m 40s	remaining: 20.7s
558:	learn: 0.0671134	total: 2m 40s	remaining: 20.4s
559:	learn: 0.0671122	total: 2m 40s	remaining: 20.1s
560:	learn: 0.0671099	total: 2m 41s	remaining: 19.8s
561:	learn: 0.0671099	total: 2m 41s	remaining: 19.5s
562:	learn: 0.0671083	total: 2m 41s	remaining: 19.2s
563:	learn: 0.0671074	total: 2m 41s	remaining: 18.9s
564:	learn: 0.0671070	total: 2m 42s	remaining: 18.6s
565:	learn: 0.0671048	total: 2m 42s	remaining: 18.4s
566:	learn: 0.0671039	total: 2m 42s	remaining: 18.1s
567:	learn: 0.0671022	total: 2m 42s	remaining: 17.8s
568:	learn: 0.0671011	total: 2m 43s	remaining: 17.5s
569:	learn: 0.0671004	total: 2m 43s	remaining: 17.2s
570:	learn: 0.0670999	total: 2m 43s	remaining: 16.9s
571:	learn: 0.0670971	total: 2m 43s	remaining: 16.6s
572:	learn: 0.0670931	total: 2m 44s	remaining: 16.3s
573:	learn: 0.0670919	total: 2m 44s	remaining: 16s
574:	learn: 0.0670917	total: 2m 44s	remaining: 15.8s
575:	learn: 0.0670881	total: 2m 44s	remaining: 15.5s
576:	learn: 0.0670869	total: 2m 45s	remaining: 15.2s
577:	learn: 0.0670849	total: 2m 45s	remaining: 14.9s
578:	learn: 0.0670841	total: 2m 45s	remaining: 14.6s
579:	learn: 0.0670829	total: 2m 46s	remaining: 14.3s
580:	learn: 0.0670818	total: 2m 46s	remaining: 14s
581:	learn: 0.0670802	total: 2m 46s	remaining: 13.7s
582:	learn: 0.0670794	total: 2m 46s	remaining: 13.4s
583:	learn: 0.0670777	total: 2m 47s	remaining: 13.2s
584:	learn: 0.0670772	total: 2m 47s	remaining: 12.9s
585:	learn: 0.0670762	total: 2m 47s	remaining: 12.6s
586:	learn: 0.0670751	total: 2m 48s	remaining: 12.3s
587:	learn: 0.0670743	total: 2m 48s	remaining: 12s
588:	learn: 0.0670738	total: 2m 48s	remaining: 11.7s
589:	learn: 0.0670706	total: 2m 49s	remaining: 11.5s
590:	learn: 0.0670675	total: 2m 49s	remaining: 11.2s
591:	learn: 0.0670662	total: 2m 50s	remaining: 10.9s
592:	learn: 0.0670651	total: 2m 50s	remaining: 10.6s
593:	learn: 0.0670643	total: 2m 50s	remaining: 10.3s
594:	learn: 0.0670635	total: 2m 50s	remaining: 10.1s
595:	learn: 0.0670624	total: 2m 51s	remaining: 9.77s
596:	learn: 0.0670587	total: 2m 51s	remaining: 9.48s
597:	learn: 0.0670556	total: 2m 51s	remaining: 9.19s
598:	learn: 0.0670521	total: 2m 52s	remaining: 8.9s
599:	learn: 0.0670506	total: 2m 52s	remaining: 8.62s
600:	learn: 0.0670499	total: 2m 52s	remaining: 8.33s
601:	learn: 0.0670495	total: 2m 52s	remaining: 8.04s
602:	learn: 0.0670483	total: 2m 53s	remaining: 7.75s
603:	learn: 0.0670472	total: 2m 53s	remaining: 7.46s
604:	learn: 0.0670444	total: 2m 53s	remaining: 7.17s
605:	learn: 0.0670429	total: 2m 53s	remaining: 6.88s
606:	learn: 0.0670426	total: 2m 54s	remaining: 6.6s
607:	learn: 0.0670417	total: 2m 54s	remaining: 6.31s
608:	learn: 0.0670402	total: 2m 54s	remaining: 6.02s
609:	learn: 0.0670377	total: 2m 54s	remaining: 5.73s
610:	learn: 0.0670367	total: 2m 55s	remaining: 5.45s
611:	learn: 0.0670317	total: 2m 55s	remaining: 5.16s
612:	learn: 0.0670281	total: 2m 55s	remaining: 4.87s
613:	learn: 0.0670271	total: 2m 55s	remaining: 4.58s
614:	learn: 0.0670248	total: 2m 56s	remaining: 4.3s
615:	learn: 0.0670223	total: 2m 56s	remaining: 4.01s
616:	learn: 0.0670214	total: 2m 56s	remaining: 3.72s
617:	learn: 0.0670170	total: 2m 57s	remaining: 3.44s
618:	learn: 0.0670166	total: 2m 57s	remaining: 3.15s
619:	learn: 0.0670147	total: 2m 57s	remaining: 2.86s
620:	learn: 0.0670124	total: 2m 57s	remaining: 2.58s
621:	learn: 0.0670105	total: 2m 58s	remaining: 2.29s
622:	learn: 0.0670095	total: 2m 58s	remaining: 2s
623:	learn: 0.0670091	total: 2m 58s	remaining: 1.72s

624:	learn: 0.0670084	total: 2m 59s	remaining: 1.44s
625:	learn: 0.0670047	total: 2m 59s	remaining: 1.15s
626:	learn: 0.0670032	total: 3m	remaining: 862ms
627:	learn: 0.0670028	total: 3m	remaining: 575ms
628:	learn: 0.0670026	total: 3m	remaining: 287ms
629:	learn: 0.0670012	total: 3m 1s	remaining: 0us

In [37]:
submission = pd.DataFrame({
    'ParcelId': test_df['ParcelId'],
})
test_dates = {
    '201710': pd.Timestamp('2017-09-30')
}
for label, test_date in test_dates.items():
    print("Predicting for: %s ... " % (label))
    submission[label] = y_pred
    
submission.to_csv(data_path + 'Model_2_CatBoost.csv', float_format='%.6f',index=False)

Predicting for: 201710 ...

In [38]:
predictions_model_1 = pd.read_csv(data_path + 'Model_2_CatBoost.csv')
predictions_model_1.head()

   ParcelId    201710
0  10754147  0.008218
1  10759547 -0.006502
2  10843547  0.033699
3  10859147  0.026486
4  10879947  0.002748