## CAT BOOST REGRESSOR

In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()
import zipfile
import re
from scipy import stats
from catboost import CatBoostRegressor
from tqdm import tqdm
import gc
import datetime as dt

<font color = blue> Once we have imported the necessary libraries, we are going to define our data path and then, load the data: </font>

In [2]:
data_path = './data/'

In [3]:
print('Loading Properties ...')
properties2016 = pd.read_csv(data_path + 'properties_2016.csv', low_memory = False)
properties2017 = pd.read_csv(data_path + 'properties_2017.csv', low_memory = False)

Loading Properties ...

In [4]:
properties2016.head()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2015.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,650756.0,1413387.0,2015.0,762631.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,7.0,NaN,NaN,...,1.0,NaN,571346.0,1156834.0,2015.0,585488.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,NaN,NaN,193796.0,433491.0,2015.0,239695.0,5725.17,NaN,NaN,NaN

In [5]:
properties2016.shape

(2985217, 58)

In [6]:
properties2017.head()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2016.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,5.0,NaN,NaN,NaN,...,1.0,NaN,660680.0,1434941.0,2016.0,774261.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,6.0,NaN,NaN,...,1.0,NaN,580059.0,1174475.0,2016.0,594416.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,1.0,NaN,196751.0,440101.0,2016.0,243350.0,5725.17,NaN,NaN,NaN

In [7]:
properties2017.shape

(2985217, 58)

<font color = blue> We are going to specify the parameter 'parse_dates' to make the column 'transactiondate' in train files date formatted: </font>

In [8]:
print('Loading Train ...')
train2016 = pd.read_csv(data_path + 'train_2016_v2.csv', parse_dates=['transactiondate'], low_memory=False)
train2017 = pd.read_csv(data_path + 'train_2017.csv', parse_dates=['transactiondate'], low_memory=False)

Loading Train ...

In [9]:
train2016.shape

(90275, 3)

In [10]:
train2017.shape

(77613, 3)

In [11]:
train2016.head()

   parcelid  logerror transactiondate
0  11016594    0.0276      2016-01-01
1  14366692   -0.1684      2016-01-01
2  12098116   -0.0040      2016-01-01
3  12643413    0.0218      2016-01-02
4  14432541   -0.0050      2016-01-02

<font color = blue> Now we are going to parse dates to get one column for year, one for month, one for day and one for quarter: </font>

In [12]:
def add_date_features(df):
    df["transaction_year"] = df["transactiondate"].dt.year
    df["transaction_month"] = (df["transactiondate"].dt.year - 2016)*12 + df["transactiondate"].dt.month
    df["transaction_day"] = df["transactiondate"].dt.day
    df["transaction_quarter"] = (df["transactiondate"].dt.year - 2016)*4 + df["transactiondate"].dt.quarter
    df.drop(["transactiondate"], inplace=True, axis=1)
    return df

In [13]:
train2016 = add_date_features(train2016)
train2017 = add_date_features(train2017)

In [14]:
train2016.head()

,parcelid,logerror,transaction_year,transaction_month,transaction_day,transaction_quarter
0,11016594,0.0276,2016,1,1,1
1,14366692,-0.1684,2016,1,1,1
2,12098116,-0.0040,2016,1,1,1
3,12643413,0.0218,2016,1,2,1
4,14432541,-0.0050,2016,1,2,1

In [15]:
print('Loading Sample ...')
sample_submission = pd.read_csv(data_path + 'sample_submission.csv', low_memory = False)

Loading Sample ...

<font color = blue> Our sample submission will be a file with the parcel id for each property and six prediction columns for different dates (last 2016 quarter and last 2017 quarter): </font>

In [16]:
sample_submission.head()

   ParcelId  201610  201611  201612  201710  201711  201712
0  10754147       0       0       0       0       0       0
1  10759547       0       0       0       0       0       0
2  10843547       0       0       0       0       0       0
3  10859147       0       0       0       0       0       0
4  10879947       0       0       0       0       0       0

<font color = blue> As we are going to apply the first model, cat boost, to the column for 201610 predictions, we remove the other columns: </font>

In [17]:
sample_submission_model_1 = sample_submission.drop(columns = ['201611', '201612', '201710', '201711', '201712'])
sample_submission_model_1.head()

   ParcelId  201610
0  10754147       0
1  10759547       0
2  10843547       0
3  10859147       0
4  10879947       0

<font color = blue> We will merge properties and train files to get all data grouped: </font>

In [18]:
print('Merging Train with Properties ...')
train2016 = pd.merge(train2016, properties2016, how = 'left', on = 'parcelid')
train2017 = pd.merge(train2017, properties2017, how = 'left', on = 'parcelid')

Merging Train with Properties ...

In [19]:
train2016.head()

,parcelid,logerror,transaction_year,transaction_month,transaction_day,transaction_quarter,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,11016594,0.0276,2016,1,1,1,1.0,NaN,NaN,2.0,...,NaN,NaN,122754.0,360170.0,2015.0,237416.0,6735.88,NaN,NaN,6.037107e+13
1,14366692,-0.1684,2016,1,1,1,NaN,NaN,NaN,3.5,...,NaN,NaN,346458.0,585529.0,2015.0,239071.0,10153.02,NaN,NaN,NaN
2,12098116,-0.0040,2016,1,1,1,1.0,NaN,NaN,3.0,...,NaN,NaN,61994.0,119906.0,2015.0,57912.0,11484.48,NaN,NaN,6.037464e+13
3,12643413,0.0218,2016,1,2,1,1.0,NaN,NaN,2.0,...,NaN,NaN,171518.0,244880.0,2015.0,73362.0,3048.74,NaN,NaN,6.037296e+13
4,14432541,-0.0050,2016,1,2,1,NaN,NaN,NaN,2.5,...,2.0,NaN,169574.0,434551.0,2015.0,264977.0,5488.96,NaN,NaN,6.059042e+13

In [20]:
train2016.shape

(90275, 63)

In [21]:
train2017.head()

,parcelid,logerror,transaction_year,transaction_month,transaction_day,transaction_quarter,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,14297519,0.025595,2017,13,1,5,NaN,NaN,NaN,3.5,...,NaN,NaN,485713.0,1023282.0,2016.0,537569.0,11013.72,NaN,NaN,6.059063e+13
1,17052889,0.055619,2017,13,1,5,NaN,NaN,NaN,1.0,...,1.0,NaN,88000.0,464000.0,2016.0,376000.0,5672.48,NaN,NaN,6.111001e+13
2,14186244,0.005383,2017,13,1,5,NaN,NaN,NaN,2.0,...,1.0,NaN,85289.0,564778.0,2016.0,479489.0,6488.30,NaN,NaN,6.059022e+13
3,12177905,-0.103410,2017,13,1,5,NaN,NaN,NaN,3.0,...,NaN,NaN,108918.0,145143.0,2016.0,36225.0,1777.51,NaN,NaN,6.037300e+13
4,10887214,0.006940,2017,13,1,5,1.0,NaN,NaN,3.0,...,NaN,NaN,73681.0,119407.0,2016.0,45726.0,1533.89,NaN,NaN,6.037124e+13

In [22]:
train2017.shape

(77613, 63)

<font color = blue> As we should not use the 2016 tax values when predicting log errors against the 2016 log errors, we will omit this information for the 2016 predicitons columns: </font>

In [23]:
print('Tax Features 2017  ...')
train2017.iloc[:, train2017.columns.str.startswith('tax')] = np.nan
train2017.iloc[:, train2017.columns.str.endswith('taxvaluedollarcnt')] = np.nan

Tax Features 2017  ...

In [24]:
train2017.head()

,parcelid,logerror,transaction_year,transaction_month,transaction_day,transaction_quarter,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,14297519,0.025595,2017,13,1,5,NaN,NaN,NaN,3.5,...,NaN,NaN,NaN,NaN,2016.0,NaN,NaN,NaN,NaN,6.059063e+13
1,17052889,0.055619,2017,13,1,5,NaN,NaN,NaN,1.0,...,1.0,NaN,NaN,NaN,2016.0,NaN,NaN,NaN,NaN,6.111001e+13
2,14186244,0.005383,2017,13,1,5,NaN,NaN,NaN,2.0,...,1.0,NaN,NaN,NaN,2016.0,NaN,NaN,NaN,NaN,6.059022e+13
3,12177905,-0.103410,2017,13,1,5,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,2016.0,NaN,NaN,NaN,NaN,6.037300e+13
4,10887214,0.006940,2017,13,1,5,1.0,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,2016.0,NaN,NaN,NaN,NaN,6.037124e+13

<font color = blue> Now we will generate our training and test files to run the model, the training file will be all properties and train from 2016 and 2017, while for the test, we will merge the sample submission with the unique properties file: </font>

In [25]:
print('Concat Train 2016 & 2017 ...')
train_df = pd.concat([train2016, train2017], axis = 0)
test_df = pd.merge(sample_submission_model_1[['ParcelId']], properties2016.rename(columns = {'parcelid': 'ParcelId'}), how = 'left', on = 'ParcelId')

Concat Train 2016 & 2017 ...

In [26]:
train_df.head()

,parcelid,logerror,transaction_year,transaction_month,transaction_day,transaction_quarter,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,11016594,0.0276,2016,1,1,1,1.0,NaN,NaN,2.0,...,NaN,NaN,122754.0,360170.0,2015.0,237416.0,6735.88,NaN,NaN,6.037107e+13
1,14366692,-0.1684,2016,1,1,1,NaN,NaN,NaN,3.5,...,NaN,NaN,346458.0,585529.0,2015.0,239071.0,10153.02,NaN,NaN,NaN
2,12098116,-0.0040,2016,1,1,1,1.0,NaN,NaN,3.0,...,NaN,NaN,61994.0,119906.0,2015.0,57912.0,11484.48,NaN,NaN,6.037464e+13
3,12643413,0.0218,2016,1,2,1,1.0,NaN,NaN,2.0,...,NaN,NaN,171518.0,244880.0,2015.0,73362.0,3048.74,NaN,NaN,6.037296e+13
4,14432541,-0.0050,2016,1,2,1,NaN,NaN,NaN,2.5,...,2.0,NaN,169574.0,434551.0,2015.0,264977.0,5488.96,NaN,NaN,6.059042e+13

In [27]:
train_df.shape

(167888, 63)

In [28]:
test_df.head()

,ParcelId,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2015.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,650756.0,1413387.0,2015.0,762631.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,7.0,NaN,NaN,...,1.0,NaN,571346.0,1156834.0,2015.0,585488.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,NaN,NaN,193796.0,433491.0,2015.0,239695.0,5725.17,NaN,NaN,NaN

In [29]:
test_df.shape

(2985217, 58)

<font color = blue> To optimize memory management, we are using garbage collections algorithms (GC), which solve reference cycles (when one or more objects are referencing each other) that reference counting cannot detect: </font>

In [30]:
del properties2016, properties2017, train2016, train2017
gc.collect();

<font color = blue> Let's do some feature engineering. We have to deal with missing values, where we will establish a threshold of 98% missing values to remove those fields, and also with features with one unique value and others that we do not want to use in our training: </font>

In [31]:
print('Missing data fields to remove ...')
missing_perc_thresh = 0.98
exclude_missing = []
num_rows = train_df.shape[0]
for c in train_df.columns:
    num_missing = train_df[c].isnull().sum()
    if num_missing == 0:
        continue
    missing_frac = num_missing / float(num_rows)
    if missing_frac > missing_perc_thresh:
        exclude_missing.append(c)
print(exclude_missing)
print("We exclude: %s" % len(exclude_missing))

Missing data fields to remove ...
['architecturalstyletypeid', 'basementsqft', 'buildingclasstypeid', 'decktypeid', 'finishedsquarefeet13', 'finishedsquarefeet6', 'poolsizesum', 'pooltypeid10', 'pooltypeid2', 'storytypeid', 'typeconstructiontypeid', 'yardbuildingsqft26', 'fireplaceflag', 'taxdelinquencyflag', 'taxdelinquencyyear']
We exclude: 15

In [32]:
print ("Remove features with one unique value ...")
exclude_unique = []
for c in train_df.columns:
    num_uniques = len(train_df[c].unique())
    if train_df[c].isnull().sum() != 0:
        num_uniques -= 1
    if num_uniques == 1:
        exclude_unique.append(c)
print(exclude_unique)
print("We exclude: %s" % len(exclude_unique))

Remove features with one unique value ...
['decktypeid', 'hashottuborspa', 'poolcnt', 'pooltypeid10', 'pooltypeid2', 'pooltypeid7', 'storytypeid', 'fireplaceflag', 'taxdelinquencyflag']
We exclude: 9

In [33]:
del num_rows, missing_perc_thresh
gc.collect();

In [34]:
print ("Define training features ...")
exclude_other = ['parcelid', 'logerror', 'propertyzoningdesc']
train_features = []
for c in train_df.columns:
    if c not in exclude_missing \
       and c not in exclude_other:
        train_features.append(c)
print(train_features)
print("We use these for training: %s" % len(train_features))

Define training features ...
['transaction_year', 'transaction_month', 'transaction_day', 'transaction_quarter', 'airconditioningtypeid', 'bathroomcnt', 'bedroomcnt', 'buildingqualitytypeid', 'calculatedbathnbr', 'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet', 'finishedsquarefeet12', 'finishedsquarefeet15', 'finishedsquarefeet50', 'fips', 'fireplacecnt', 'fullbathcnt', 'garagecarcnt', 'garagetotalsqft', 'hashottuborspa', 'heatingorsystemtypeid', 'latitude', 'longitude', 'lotsizesquarefeet', 'poolcnt', 'pooltypeid7', 'propertycountylandusecode', 'propertylandusetypeid', 'rawcensustractandblock', 'regionidcity', 'regionidcounty', 'regionidneighborhood', 'regionidzip', 'roomcnt', 'threequarterbathnbr', 'unitcnt', 'yardbuildingsqft17', 'yearbuilt', 'numberofstories', 'structuretaxvaluedollarcnt', 'taxvaluedollarcnt', 'assessmentyear', 'landtaxvaluedollarcnt', 'taxamount', 'censustractandblock']
We use these for training: 45

<font color = blue> Now we have to deal with categorical features: </font>

In [35]:
print ("Define categorical features ...")
cat_feature_inds = []
cat_unique_thresh = 100
for i, c in enumerate(train_features):
    num_uniques = len(train_df[c].unique())
    if num_uniques < cat_unique_thresh \
       and not 'sqft' in c \
       and not 'cnt' in c \
       and not 'nbr' in c \
       and not 'number' in c:
        cat_feature_inds.append(i)
print("Cat features are: %s" % [train_features[ind] for ind in cat_feature_inds])

Define categorical features ...
Cat features are: ['transaction_year', 'transaction_month', 'transaction_day', 'transaction_quarter', 'airconditioningtypeid', 'buildingqualitytypeid', 'fips', 'hashottuborspa', 'heatingorsystemtypeid', 'pooltypeid7', 'propertycountylandusecode', 'propertylandusetypeid', 'regionidcounty', 'assessmentyear']

<font color = blue> As we are going to use a tree based model, we will replace NaN values by '-999' so they do not interfere with proper data: </font>

In [36]:
print ("Replacing NaN values by -999 ...")
train_df.fillna(-999, inplace=True)
test_df.fillna(-999, inplace=True)

Replacing NaN values by -999 ...

<font color = blue> Training start: </font>

In [37]:
print ("Training model 1: Cat boost ...")
X_train = train_df[train_features]
y_train = train_df.logerror
print(X_train.shape, y_train.shape)

test_df['transactiondate'] = pd.Timestamp('2016-12-01') 
test_df = add_date_features(test_df)
X_test = test_df[train_features]
print(X_test.shape)

Training model 1: Cat boost ...
(167888, 45) (167888,)
(2985217, 45)

In [38]:
y_pred = 0.0
model = CatBoostRegressor(
    iterations = 630, learning_rate = 0.02,
    depth = 6, l2_leaf_reg = 3,
    loss_function = 'MAE',
    eval_metric = 'MAE',
    random_seed = i)
model.fit(
    X_train, y_train,
    cat_features = cat_feature_inds)
y_pred += model.predict(X_test)

0:	learn: 0.0690001	total: 375ms	remaining: 3m 56s
1:	learn: 0.0688399	total: 685ms	remaining: 3m 35s
2:	learn: 0.0687483	total: 983ms	remaining: 3m 25s
3:	learn: 0.0686686	total: 1.28s	remaining: 3m 19s
4:	learn: 0.0686167	total: 1.53s	remaining: 3m 11s
5:	learn: 0.0685816	total: 1.78s	remaining: 3m 5s
6:	learn: 0.0685585	total: 2s	remaining: 2m 58s
7:	learn: 0.0685155	total: 2.33s	remaining: 3m
8:	learn: 0.0684961	total: 2.62s	remaining: 3m
9:	learn: 0.0684639	total: 2.98s	remaining: 3m 4s
10:	learn: 0.0684445	total: 3.28s	remaining: 3m 4s
11:	learn: 0.0684140	total: 3.66s	remaining: 3m 8s
12:	learn: 0.0683899	total: 4.46s	remaining: 3m 31s
13:	learn: 0.0683743	total: 4.87s	remaining: 3m 34s
14:	learn: 0.0683660	total: 5.2s	remaining: 3m 33s
15:	learn: 0.0683579	total: 5.5s	remaining: 3m 30s
16:	learn: 0.0683425	total: 5.79s	remaining: 3m 28s
17:	learn: 0.0683308	total: 6.07s	remaining: 3m 26s
18:	learn: 0.0683150	total: 6.4s	remaining: 3m 25s
19:	learn: 0.0683001	total: 6.71s	remaining: 3m 24s
20:	learn: 0.0682898	total: 6.96s	remaining: 3m 21s
21:	learn: 0.0682834	total: 7.21s	remaining: 3m 19s
22:	learn: 0.0682679	total: 7.49s	remaining: 3m 17s
23:	learn: 0.0682603	total: 7.76s	remaining: 3m 15s
24:	learn: 0.0682535	total: 8s	remaining: 3m 13s
25:	learn: 0.0682412	total: 8.26s	remaining: 3m 11s
26:	learn: 0.0682320	total: 8.51s	remaining: 3m 9s
27:	learn: 0.0682239	total: 8.81s	remaining: 3m 9s
28:	learn: 0.0682192	total: 9.06s	remaining: 3m 7s
29:	learn: 0.0682067	total: 9.34s	remaining: 3m 6s
30:	learn: 0.0681994	total: 9.59s	remaining: 3m 5s
31:	learn: 0.0681944	total: 9.86s	remaining: 3m 4s
32:	learn: 0.0681810	total: 10.1s	remaining: 3m 2s
33:	learn: 0.0681720	total: 10.3s	remaining: 3m 1s
34:	learn: 0.0681658	total: 10.6s	remaining: 3m
35:	learn: 0.0681617	total: 11s	remaining: 3m
36:	learn: 0.0681576	total: 11.3s	remaining: 3m
37:	learn: 0.0681490	total: 11.5s	remaining: 2m 59s
38:	learn: 0.0681440	total: 11.8s	remaining: 2m 58s
39:	learn: 0.0681389	total: 12s	remaining: 2m 57s
40:	learn: 0.0681312	total: 12.3s	remaining: 2m 56s
41:	learn: 0.0681236	total: 12.5s	remaining: 2m 55s
42:	learn: 0.0681185	total: 12.9s	remaining: 2m 55s
43:	learn: 0.0681143	total: 13.2s	remaining: 2m 55s
44:	learn: 0.0681113	total: 13.5s	remaining: 2m 56s
45:	learn: 0.0681037	total: 13.9s	remaining: 2m 55s
46:	learn: 0.0680954	total: 14.8s	remaining: 3m 4s
47:	learn: 0.0680921	total: 15.2s	remaining: 3m 3s
48:	learn: 0.0680829	total: 15.5s	remaining: 3m 3s
49:	learn: 0.0680751	total: 15.7s	remaining: 3m 2s
50:	learn: 0.0680699	total: 16s	remaining: 3m 1s
51:	learn: 0.0680657	total: 16.3s	remaining: 3m
52:	learn: 0.0680648	total: 16.5s	remaining: 3m
53:	learn: 0.0680608	total: 16.8s	remaining: 2m 59s
54:	learn: 0.0680555	total: 17.1s	remaining: 2m 58s
55:	learn: 0.0680529	total: 17.3s	remaining: 2m 57s
56:	learn: 0.0680416	total: 17.6s	remaining: 2m 57s
57:	learn: 0.0680359	total: 17.9s	remaining: 2m 56s
58:	learn: 0.0680299	total: 18.1s	remaining: 2m 55s
59:	learn: 0.0680202	total: 18.3s	remaining: 2m 54s
60:	learn: 0.0680175	total: 18.6s	remaining: 2m 53s
61:	learn: 0.0680118	total: 18.9s	remaining: 2m 52s
62:	learn: 0.0680081	total: 19.1s	remaining: 2m 52s
63:	learn: 0.0680052	total: 19.4s	remaining: 2m 51s
64:	learn: 0.0680043	total: 19.6s	remaining: 2m 50s
65:	learn: 0.0680011	total: 19.9s	remaining: 2m 50s
66:	learn: 0.0679995	total: 20.2s	remaining: 2m 49s
67:	learn: 0.0679975	total: 20.4s	remaining: 2m 48s
68:	learn: 0.0679960	total: 20.6s	remaining: 2m 47s
69:	learn: 0.0679909	total: 20.9s	remaining: 2m 47s
70:	learn: 0.0679881	total: 21.2s	remaining: 2m 46s
71:	learn: 0.0679838	total: 21.4s	remaining: 2m 46s
72:	learn: 0.0679806	total: 21.7s	remaining: 2m 45s
73:	learn: 0.0679775	total: 22s	remaining: 2m 45s
74:	learn: 0.0679733	total: 22.3s	remaining: 2m 44s
75:	learn: 0.0679698	total: 22.5s	remaining: 2m 44s
76:	learn: 0.0679678	total: 22.8s	remaining: 2m 43s
77:	learn: 0.0679645	total: 23s	remaining: 2m 42s
78:	learn: 0.0679618	total: 23.3s	remaining: 2m 42s
79:	learn: 0.0679570	total: 23.6s	remaining: 2m 42s
80:	learn: 0.0679552	total: 23.9s	remaining: 2m 42s
81:	learn: 0.0679542	total: 24.2s	remaining: 2m 41s
82:	learn: 0.0679482	total: 24.6s	remaining: 2m 41s
83:	learn: 0.0679417	total: 25.4s	remaining: 2m 45s
84:	learn: 0.0679399	total: 25.8s	remaining: 2m 45s
85:	learn: 0.0679386	total: 26.1s	remaining: 2m 44s
86:	learn: 0.0679348	total: 26.3s	remaining: 2m 44s
87:	learn: 0.0679321	total: 26.6s	remaining: 2m 43s
88:	learn: 0.0679318	total: 26.7s	remaining: 2m 42s
89:	learn: 0.0679288	total: 26.9s	remaining: 2m 41s
90:	learn: 0.0679262	total: 27.2s	remaining: 2m 41s
91:	learn: 0.0679212	total: 27.5s	remaining: 2m 40s
92:	learn: 0.0679170	total: 27.7s	remaining: 2m 40s
93:	learn: 0.0679136	total: 28s	remaining: 2m 39s
94:	learn: 0.0679136	total: 28.1s	remaining: 2m 38s
95:	learn: 0.0679125	total: 28.3s	remaining: 2m 37s
96:	learn: 0.0679115	total: 28.5s	remaining: 2m 36s
97:	learn: 0.0679076	total: 28.8s	remaining: 2m 36s
98:	learn: 0.0679043	total: 29s	remaining: 2m 35s
99:	learn: 0.0678990	total: 29.3s	remaining: 2m 35s
100:	learn: 0.0678983	total: 29.5s	remaining: 2m 34s
101:	learn: 0.0678963	total: 29.8s	remaining: 2m 34s
102:	learn: 0.0678949	total: 30s	remaining: 2m 33s
103:	learn: 0.0678942	total: 30.3s	remaining: 2m 33s
104:	learn: 0.0678922	total: 30.6s	remaining: 2m 33s
105:	learn: 0.0678863	total: 31s	remaining: 2m 33s
106:	learn: 0.0678851	total: 31.2s	remaining: 2m 32s
107:	learn: 0.0678833	total: 31.4s	remaining: 2m 31s
108:	learn: 0.0678797	total: 31.7s	remaining: 2m 31s
109:	learn: 0.0678769	total: 32.1s	remaining: 2m 31s
110:	learn: 0.0678744	total: 32.5s	remaining: 2m 31s
111:	learn: 0.0678740	total: 32.8s	remaining: 2m 31s
112:	learn: 0.0678724	total: 33s	remaining: 2m 31s
113:	learn: 0.0678713	total: 33.4s	remaining: 2m 31s
114:	learn: 0.0678662	total: 33.8s	remaining: 2m 31s
115:	learn: 0.0678614	total: 34.3s	remaining: 2m 31s
116:	learn: 0.0678596	total: 34.7s	remaining: 2m 31s
117:	learn: 0.0678569	total: 35.2s	remaining: 2m 32s
118:	learn: 0.0678540	total: 36.2s	remaining: 2m 35s
119:	learn: 0.0678510	total: 36.5s	remaining: 2m 35s
120:	learn: 0.0678486	total: 36.9s	remaining: 2m 35s
121:	learn: 0.0678467	total: 37.3s	remaining: 2m 35s
122:	learn: 0.0678453	total: 37.6s	remaining: 2m 35s
123:	learn: 0.0678429	total: 37.9s	remaining: 2m 34s
124:	learn: 0.0678404	total: 38.2s	remaining: 2m 34s
125:	learn: 0.0678362	total: 38.5s	remaining: 2m 33s
126:	learn: 0.0678353	total: 38.8s	remaining: 2m 33s
127:	learn: 0.0678344	total: 39.1s	remaining: 2m 33s
128:	learn: 0.0678308	total: 39.4s	remaining: 2m 33s
129:	learn: 0.0678292	total: 39.6s	remaining: 2m 32s
130:	learn: 0.0678291	total: 39.9s	remaining: 2m 31s
131:	learn: 0.0678248	total: 40.1s	remaining: 2m 31s
132:	learn: 0.0678231	total: 40.4s	remaining: 2m 30s
133:	learn: 0.0678217	total: 40.6s	remaining: 2m 30s
134:	learn: 0.0678178	total: 40.9s	remaining: 2m 30s
135:	learn: 0.0678155	total: 41.2s	remaining: 2m 29s
136:	learn: 0.0678123	total: 41.5s	remaining: 2m 29s
137:	learn: 0.0678091	total: 41.8s	remaining: 2m 28s
138:	learn: 0.0678024	total: 42s	remaining: 2m 28s
139:	learn: 0.0677997	total: 42.3s	remaining: 2m 27s
140:	learn: 0.0677992	total: 42.5s	remaining: 2m 27s
141:	learn: 0.0677974	total: 42.7s	remaining: 2m 26s
142:	learn: 0.0677932	total: 43s	remaining: 2m 26s
143:	learn: 0.0677899	total: 43.2s	remaining: 2m 25s
144:	learn: 0.0677880	total: 43.5s	remaining: 2m 25s
145:	learn: 0.0677851	total: 43.8s	remaining: 2m 25s
146:	learn: 0.0677840	total: 44.1s	remaining: 2m 24s
147:	learn: 0.0677831	total: 44.4s	remaining: 2m 24s
148:	learn: 0.0677818	total: 44.8s	remaining: 2m 24s
149:	learn: 0.0677773	total: 45.3s	remaining: 2m 25s
150:	learn: 0.0677760	total: 45.7s	remaining: 2m 24s
151:	learn: 0.0677725	total: 46.1s	remaining: 2m 24s
152:	learn: 0.0677664	total: 47s	remaining: 2m 26s
153:	learn: 0.0677658	total: 47.3s	remaining: 2m 26s
154:	learn: 0.0677611	total: 47.7s	remaining: 2m 26s
155:	learn: 0.0677589	total: 47.9s	remaining: 2m 25s
156:	learn: 0.0677576	total: 48.2s	remaining: 2m 25s
157:	learn: 0.0677545	total: 48.4s	remaining: 2m 24s
158:	learn: 0.0677528	total: 48.8s	remaining: 2m 24s

159:	learn: 0.0677523	total: 49s	remaining: 2m 24s
160:	learn: 0.0677516	total: 49.3s	remaining: 2m 23s
161:	learn: 0.0677500	total: 49.5s	remaining: 2m 23s
162:	learn: 0.0677485	total: 49.8s	remaining: 2m 22s
163:	learn: 0.0677467	total: 50.1s	remaining: 2m 22s
164:	learn: 0.0677454	total: 50.4s	remaining: 2m 21s
165:	learn: 0.0677448	total: 50.6s	remaining: 2m 21s
166:	learn: 0.0677443	total: 50.8s	remaining: 2m 20s
167:	learn: 0.0677438	total: 51.1s	remaining: 2m 20s
168:	learn: 0.0677424	total: 51.4s	remaining: 2m 20s
169:	learn: 0.0677418	total: 51.6s	remaining: 2m 19s
170:	learn: 0.0677409	total: 51.9s	remaining: 2m 19s
171:	learn: 0.0677374	total: 52.1s	remaining: 2m 18s
172:	learn: 0.0677369	total: 52.4s	remaining: 2m 18s
173:	learn: 0.0677359	total: 52.6s	remaining: 2m 17s
174:	learn: 0.0677354	total: 52.9s	remaining: 2m 17s
175:	learn: 0.0677343	total: 53.2s	remaining: 2m 17s
176:	learn: 0.0677330	total: 53.4s	remaining: 2m 16s
177:	learn: 0.0677286	total: 53.7s	remaining: 2m 16s
178:	learn: 0.0677247	total: 54s	remaining: 2m 15s
179:	learn: 0.0677245	total: 54.2s	remaining: 2m 15s
180:	learn: 0.0677230	total: 54.4s	remaining: 2m 14s
181:	learn: 0.0677216	total: 54.7s	remaining: 2m 14s
182:	learn: 0.0677206	total: 54.9s	remaining: 2m 14s
183:	learn: 0.0677192	total: 55.2s	remaining: 2m 13s
184:	learn: 0.0677176	total: 55.4s	remaining: 2m 13s
185:	learn: 0.0677149	total: 55.8s	remaining: 2m 13s
186:	learn: 0.0677145	total: 56.1s	remaining: 2m 12s
187:	learn: 0.0677136	total: 56.4s	remaining: 2m 12s
188:	learn: 0.0677106	total: 56.7s	remaining: 2m 12s
189:	learn: 0.0677061	total: 57.6s	remaining: 2m 13s
190:	learn: 0.0677026	total: 57.9s	remaining: 2m 13s
191:	learn: 0.0676991	total: 58.3s	remaining: 2m 12s
192:	learn: 0.0676985	total: 58.5s	remaining: 2m 12s
193:	learn: 0.0676971	total: 58.7s	remaining: 2m 11s
194:	learn: 0.0676956	total: 59s	remaining: 2m 11s
195:	learn: 0.0676944	total: 59.2s	remaining: 2m 11s
196:	learn: 0.0676936	total: 59.5s	remaining: 2m 10s
197:	learn: 0.0676923	total: 59.8s	remaining: 2m 10s
198:	learn: 0.0676905	total: 1m	remaining: 2m 10s
199:	learn: 0.0676863	total: 1m	remaining: 2m 9s
200:	learn: 0.0676840	total: 1m	remaining: 2m 9s
201:	learn: 0.0676805	total: 1m	remaining: 2m 8s
202:	learn: 0.0676788	total: 1m 1s	remaining: 2m 8s
203:	learn: 0.0676775	total: 1m 1s	remaining: 2m 8s
204:	learn: 0.0676764	total: 1m 1s	remaining: 2m 7s
205:	learn: 0.0676754	total: 1m 1s	remaining: 2m 7s
206:	learn: 0.0676750	total: 1m 1s	remaining: 2m 6s
207:	learn: 0.0676734	total: 1m 2s	remaining: 2m 6s
208:	learn: 0.0676712	total: 1m 2s	remaining: 2m 5s
209:	learn: 0.0676685	total: 1m 2s	remaining: 2m 5s
210:	learn: 0.0676682	total: 1m 2s	remaining: 2m 4s
211:	learn: 0.0676680	total: 1m 3s	remaining: 2m 4s
212:	learn: 0.0676644	total: 1m 3s	remaining: 2m 4s
213:	learn: 0.0676624	total: 1m 3s	remaining: 2m 3s
214:	learn: 0.0676618	total: 1m 3s	remaining: 2m 3s
215:	learn: 0.0676606	total: 1m 4s	remaining: 2m 2s
216:	learn: 0.0676592	total: 1m 4s	remaining: 2m 2s
217:	learn: 0.0676565	total: 1m 4s	remaining: 2m 2s
218:	learn: 0.0676562	total: 1m 4s	remaining: 2m 1s
219:	learn: 0.0676542	total: 1m 5s	remaining: 2m 1s
220:	learn: 0.0676504	total: 1m 5s	remaining: 2m 1s
221:	learn: 0.0676491	total: 1m 5s	remaining: 2m
222:	learn: 0.0676487	total: 1m 5s	remaining: 2m
223:	learn: 0.0676480	total: 1m 6s	remaining: 1m 59s
224:	learn: 0.0676474	total: 1m 6s	remaining: 1m 59s
225:	learn: 0.0676467	total: 1m 6s	remaining: 1m 59s
226:	learn: 0.0676447	total: 1m 7s	remaining: 1m 59s
227:	learn: 0.0676422	total: 1m 8s	remaining: 2m
228:	learn: 0.0676384	total: 1m 8s	remaining: 1m 59s
229:	learn: 0.0676372	total: 1m 8s	remaining: 1m 59s
230:	learn: 0.0676354	total: 1m 8s	remaining: 1m 58s
231:	learn: 0.0676338	total: 1m 9s	remaining: 1m 58s
232:	learn: 0.0676312	total: 1m 9s	remaining: 1m 58s
233:	learn: 0.0676259	total: 1m 9s	remaining: 1m 57s
234:	learn: 0.0676240	total: 1m 9s	remaining: 1m 57s
235:	learn: 0.0676239	total: 1m 10s	remaining: 1m 56s
236:	learn: 0.0676233	total: 1m 10s	remaining: 1m 56s
237:	learn: 0.0676226	total: 1m 10s	remaining: 1m 56s
238:	learn: 0.0676219	total: 1m 10s	remaining: 1m 55s
239:	learn: 0.0676215	total: 1m 11s	remaining: 1m 55s
240:	learn: 0.0676194	total: 1m 11s	remaining: 1m 55s
241:	learn: 0.0676192	total: 1m 11s	remaining: 1m 54s
242:	learn: 0.0676191	total: 1m 11s	remaining: 1m 54s
243:	learn: 0.0676152	total: 1m 11s	remaining: 1m 53s
244:	learn: 0.0676146	total: 1m 12s	remaining: 1m 53s
245:	learn: 0.0676127	total: 1m 12s	remaining: 1m 52s
246:	learn: 0.0676070	total: 1m 12s	remaining: 1m 52s
247:	learn: 0.0676051	total: 1m 12s	remaining: 1m 52s
248:	learn: 0.0676040	total: 1m 13s	remaining: 1m 51s
249:	learn: 0.0676002	total: 1m 13s	remaining: 1m 51s
250:	learn: 0.0675995	total: 1m 13s	remaining: 1m 51s
251:	learn: 0.0675990	total: 1m 13s	remaining: 1m 50s
252:	learn: 0.0675969	total: 1m 14s	remaining: 1m 50s
253:	learn: 0.0675962	total: 1m 14s	remaining: 1m 50s
254:	learn: 0.0675946	total: 1m 14s	remaining: 1m 49s
255:	learn: 0.0675939	total: 1m 14s	remaining: 1m 49s
256:	learn: 0.0675928	total: 1m 15s	remaining: 1m 49s
257:	learn: 0.0675907	total: 1m 15s	remaining: 1m 48s
258:	learn: 0.0675869	total: 1m 15s	remaining: 1m 48s
259:	learn: 0.0675865	total: 1m 15s	remaining: 1m 47s
260:	learn: 0.0675861	total: 1m 16s	remaining: 1m 47s
261:	learn: 0.0675861	total: 1m 16s	remaining: 1m 46s
262:	learn: 0.0675853	total: 1m 16s	remaining: 1m 46s
263:	learn: 0.0675836	total: 1m 16s	remaining: 1m 46s
264:	learn: 0.0675827	total: 1m 17s	remaining: 1m 46s
265:	learn: 0.0675810	total: 1m 17s	remaining: 1m 45s
266:	learn: 0.0675806	total: 1m 18s	remaining: 1m 46s
267:	learn: 0.0675783	total: 1m 18s	remaining: 1m 46s
268:	learn: 0.0675764	total: 1m 18s	remaining: 1m 45s
269:	learn: 0.0675763	total: 1m 19s	remaining: 1m 45s
270:	learn: 0.0675737	total: 1m 19s	remaining: 1m 45s
271:	learn: 0.0675729	total: 1m 19s	remaining: 1m 44s
272:	learn: 0.0675721	total: 1m 19s	remaining: 1m 44s
273:	learn: 0.0675694	total: 1m 20s	remaining: 1m 44s
274:	learn: 0.0675673	total: 1m 20s	remaining: 1m 43s
275:	learn: 0.0675616	total: 1m 20s	remaining: 1m 43s
276:	learn: 0.0675613	total: 1m 20s	remaining: 1m 43s
277:	learn: 0.0675599	total: 1m 21s	remaining: 1m 42s
278:	learn: 0.0675591	total: 1m 21s	remaining: 1m 42s
279:	learn: 0.0675559	total: 1m 21s	remaining: 1m 42s
280:	learn: 0.0675551	total: 1m 21s	remaining: 1m 41s
281:	learn: 0.0675548	total: 1m 22s	remaining: 1m 41s
282:	learn: 0.0675501	total: 1m 22s	remaining: 1m 40s
283:	learn: 0.0675484	total: 1m 22s	remaining: 1m 40s
284:	learn: 0.0675472	total: 1m 22s	remaining: 1m 40s
285:	learn: 0.0675455	total: 1m 23s	remaining: 1m 39s
286:	learn: 0.0675444	total: 1m 23s	remaining: 1m 39s
287:	learn: 0.0675428	total: 1m 23s	remaining: 1m 39s
288:	learn: 0.0675408	total: 1m 23s	remaining: 1m 38s
289:	learn: 0.0675405	total: 1m 23s	remaining: 1m 38s
290:	learn: 0.0675376	total: 1m 24s	remaining: 1m 38s
291:	learn: 0.0675321	total: 1m 24s	remaining: 1m 37s
292:	learn: 0.0675312	total: 1m 24s	remaining: 1m 37s
293:	learn: 0.0675279	total: 1m 24s	remaining: 1m 37s
294:	learn: 0.0675266	total: 1m 25s	remaining: 1m 36s
295:	learn: 0.0675241	total: 1m 25s	remaining: 1m 36s
296:	learn: 0.0675233	total: 1m 25s	remaining: 1m 36s
297:	learn: 0.0675226	total: 1m 25s	remaining: 1m 35s
298:	learn: 0.0675221	total: 1m 26s	remaining: 1m 35s
299:	learn: 0.0675216	total: 1m 26s	remaining: 1m 35s
300:	learn: 0.0675198	total: 1m 26s	remaining: 1m 34s
301:	learn: 0.0675170	total: 1m 27s	remaining: 1m 34s
302:	learn: 0.0675164	total: 1m 27s	remaining: 1m 34s
303:	learn: 0.0675146	total: 1m 28s	remaining: 1m 34s
304:	learn: 0.0675123	total: 1m 28s	remaining: 1m 34s
305:	learn: 0.0675117	total: 1m 29s	remaining: 1m 34s
306:	learn: 0.0675110	total: 1m 29s	remaining: 1m 33s
307:	learn: 0.0675088	total: 1m 29s	remaining: 1m 33s
308:	learn: 0.0675080	total: 1m 29s	remaining: 1m 33s
309:	learn: 0.0675066	total: 1m 30s	remaining: 1m 32s
310:	learn: 0.0675047	total: 1m 30s	remaining: 1m 32s
311:	learn: 0.0675022	total: 1m 30s	remaining: 1m 32s
312:	learn: 0.0675001	total: 1m 30s	remaining: 1m 32s
313:	learn: 0.0674987	total: 1m 31s	remaining: 1m 31s

314:	learn: 0.0674980	total: 1m 31s	remaining: 1m 31s
315:	learn: 0.0674973	total: 1m 31s	remaining: 1m 31s
316:	learn: 0.0674966	total: 1m 31s	remaining: 1m 30s
317:	learn: 0.0674964	total: 1m 32s	remaining: 1m 30s
318:	learn: 0.0674951	total: 1m 32s	remaining: 1m 29s
319:	learn: 0.0674934	total: 1m 32s	remaining: 1m 29s
320:	learn: 0.0674925	total: 1m 32s	remaining: 1m 29s
321:	learn: 0.0674920	total: 1m 33s	remaining: 1m 28s
322:	learn: 0.0674909	total: 1m 33s	remaining: 1m 28s
323:	learn: 0.0674903	total: 1m 33s	remaining: 1m 28s
324:	learn: 0.0674902	total: 1m 33s	remaining: 1m 27s
325:	learn: 0.0674890	total: 1m 33s	remaining: 1m 27s
326:	learn: 0.0674855	total: 1m 34s	remaining: 1m 27s
327:	learn: 0.0674849	total: 1m 34s	remaining: 1m 26s
328:	learn: 0.0674844	total: 1m 34s	remaining: 1m 26s
329:	learn: 0.0674838	total: 1m 34s	remaining: 1m 26s
330:	learn: 0.0674824	total: 1m 35s	remaining: 1m 25s
331:	learn: 0.0674792	total: 1m 35s	remaining: 1m 25s
332:	learn: 0.0674773	total: 1m 35s	remaining: 1m 25s
333:	learn: 0.0674752	total: 1m 35s	remaining: 1m 24s
334:	learn: 0.0674746	total: 1m 36s	remaining: 1m 24s
335:	learn: 0.0674745	total: 1m 36s	remaining: 1m 24s
336:	learn: 0.0674737	total: 1m 36s	remaining: 1m 23s
337:	learn: 0.0674729	total: 1m 36s	remaining: 1m 23s
338:	learn: 0.0674701	total: 1m 37s	remaining: 1m 23s
339:	learn: 0.0674680	total: 1m 37s	remaining: 1m 23s
340:	learn: 0.0674665	total: 1m 37s	remaining: 1m 22s
341:	learn: 0.0674611	total: 1m 38s	remaining: 1m 22s
342:	learn: 0.0674605	total: 1m 38s	remaining: 1m 22s
343:	learn: 0.0674597	total: 1m 39s	remaining: 1m 22s
344:	learn: 0.0674581	total: 1m 39s	remaining: 1m 22s
345:	learn: 0.0674566	total: 1m 39s	remaining: 1m 21s
346:	learn: 0.0674557	total: 1m 39s	remaining: 1m 21s
347:	learn: 0.0674553	total: 1m 40s	remaining: 1m 21s
348:	learn: 0.0674548	total: 1m 40s	remaining: 1m 20s
349:	learn: 0.0674541	total: 1m 40s	remaining: 1m 20s
350:	learn: 0.0674533	total: 1m 41s	remaining: 1m 20s
351:	learn: 0.0674522	total: 1m 41s	remaining: 1m 19s
352:	learn: 0.0674489	total: 1m 41s	remaining: 1m 19s
353:	learn: 0.0674479	total: 1m 41s	remaining: 1m 19s
354:	learn: 0.0674470	total: 1m 42s	remaining: 1m 19s
355:	learn: 0.0674464	total: 1m 42s	remaining: 1m 18s
356:	learn: 0.0674452	total: 1m 42s	remaining: 1m 18s
357:	learn: 0.0674433	total: 1m 42s	remaining: 1m 18s
358:	learn: 0.0674427	total: 1m 42s	remaining: 1m 17s
359:	learn: 0.0674419	total: 1m 43s	remaining: 1m 17s
360:	learn: 0.0674414	total: 1m 43s	remaining: 1m 17s
361:	learn: 0.0674371	total: 1m 43s	remaining: 1m 16s
362:	learn: 0.0674367	total: 1m 43s	remaining: 1m 16s
363:	learn: 0.0674349	total: 1m 44s	remaining: 1m 16s
364:	learn: 0.0674346	total: 1m 44s	remaining: 1m 15s
365:	learn: 0.0674338	total: 1m 44s	remaining: 1m 15s
366:	learn: 0.0674332	total: 1m 44s	remaining: 1m 15s
367:	learn: 0.0674323	total: 1m 45s	remaining: 1m 14s
368:	learn: 0.0674305	total: 1m 45s	remaining: 1m 14s
369:	learn: 0.0674296	total: 1m 45s	remaining: 1m 14s
370:	learn: 0.0674289	total: 1m 46s	remaining: 1m 14s
371:	learn: 0.0674289	total: 1m 46s	remaining: 1m 13s
372:	learn: 0.0674276	total: 1m 46s	remaining: 1m 13s
373:	learn: 0.0674261	total: 1m 46s	remaining: 1m 13s
374:	learn: 0.0674201	total: 1m 47s	remaining: 1m 12s
375:	learn: 0.0674184	total: 1m 47s	remaining: 1m 12s
376:	learn: 0.0674184	total: 1m 47s	remaining: 1m 12s
377:	learn: 0.0674169	total: 1m 47s	remaining: 1m 11s
378:	learn: 0.0674164	total: 1m 48s	remaining: 1m 11s
379:	learn: 0.0674152	total: 1m 48s	remaining: 1m 11s
380:	learn: 0.0674122	total: 1m 49s	remaining: 1m 11s
381:	learn: 0.0674122	total: 1m 49s	remaining: 1m 10s
382:	learn: 0.0674112	total: 1m 49s	remaining: 1m 10s
383:	learn: 0.0674093	total: 1m 50s	remaining: 1m 10s
384:	learn: 0.0674084	total: 1m 50s	remaining: 1m 10s
385:	learn: 0.0674056	total: 1m 50s	remaining: 1m 9s
386:	learn: 0.0674025	total: 1m 50s	remaining: 1m 9s
387:	learn: 0.0674021	total: 1m 51s	remaining: 1m 9s
388:	learn: 0.0674010	total: 1m 51s	remaining: 1m 8s
389:	learn: 0.0674001	total: 1m 51s	remaining: 1m 8s
390:	learn: 0.0673986	total: 1m 51s	remaining: 1m 8s
391:	learn: 0.0673981	total: 1m 52s	remaining: 1m 8s
392:	learn: 0.0673974	total: 1m 52s	remaining: 1m 7s
393:	learn: 0.0673958	total: 1m 52s	remaining: 1m 7s
394:	learn: 0.0673940	total: 1m 52s	remaining: 1m 7s
395:	learn: 0.0673936	total: 1m 53s	remaining: 1m 6s
396:	learn: 0.0673917	total: 1m 53s	remaining: 1m 6s
397:	learn: 0.0673907	total: 1m 53s	remaining: 1m 6s
398:	learn: 0.0673890	total: 1m 53s	remaining: 1m 5s
399:	learn: 0.0673889	total: 1m 54s	remaining: 1m 5s
400:	learn: 0.0673886	total: 1m 54s	remaining: 1m 5s
401:	learn: 0.0673878	total: 1m 54s	remaining: 1m 4s
402:	learn: 0.0673870	total: 1m 54s	remaining: 1m 4s
403:	learn: 0.0673861	total: 1m 55s	remaining: 1m 4s
404:	learn: 0.0673836	total: 1m 55s	remaining: 1m 4s
405:	learn: 0.0673821	total: 1m 55s	remaining: 1m 3s
406:	learn: 0.0673795	total: 1m 55s	remaining: 1m 3s
407:	learn: 0.0673788	total: 1m 56s	remaining: 1m 3s
408:	learn: 0.0673767	total: 1m 56s	remaining: 1m 2s
409:	learn: 0.0673756	total: 1m 56s	remaining: 1m 2s
410:	learn: 0.0673748	total: 1m 56s	remaining: 1m 2s
411:	learn: 0.0673745	total: 1m 57s	remaining: 1m 1s
412:	learn: 0.0673732	total: 1m 57s	remaining: 1m 1s
413:	learn: 0.0673711	total: 1m 57s	remaining: 1m 1s
414:	learn: 0.0673705	total: 1m 57s	remaining: 1m 1s
415:	learn: 0.0673703	total: 1m 58s	remaining: 1m
416:	learn: 0.0673699	total: 1m 58s	remaining: 1m
417:	learn: 0.0673641	total: 1m 58s	remaining: 1m
418:	learn: 0.0673640	total: 1m 59s	remaining: 1m
419:	learn: 0.0673635	total: 1m 59s	remaining: 60s
420:	learn: 0.0673618	total: 2m	remaining: 59.7s
421:	learn: 0.0673608	total: 2m	remaining: 59.4s
422:	learn: 0.0673569	total: 2m	remaining: 59.1s
423:	learn: 0.0673532	total: 2m 1s	remaining: 58.8s
424:	learn: 0.0673522	total: 2m 1s	remaining: 58.5s
425:	learn: 0.0673501	total: 2m 1s	remaining: 58.2s
426:	learn: 0.0673496	total: 2m 1s	remaining: 57.9s
427:	learn: 0.0673485	total: 2m 2s	remaining: 57.6s
428:	learn: 0.0673470	total: 2m 2s	remaining: 57.3s
429:	learn: 0.0673459	total: 2m 2s	remaining: 57s
430:	learn: 0.0673449	total: 2m 2s	remaining: 56.7s
431:	learn: 0.0673435	total: 2m 3s	remaining: 56.4s
432:	learn: 0.0673396	total: 2m 3s	remaining: 56.2s
433:	learn: 0.0673389	total: 2m 3s	remaining: 55.9s
434:	learn: 0.0673377	total: 2m 3s	remaining: 55.5s
435:	learn: 0.0673366	total: 2m 4s	remaining: 55.3s
436:	learn: 0.0673338	total: 2m 4s	remaining: 55s
437:	learn: 0.0673331	total: 2m 4s	remaining: 54.7s
438:	learn: 0.0673327	total: 2m 4s	remaining: 54.4s
439:	learn: 0.0673301	total: 2m 5s	remaining: 54.1s
440:	learn: 0.0673297	total: 2m 5s	remaining: 53.8s
441:	learn: 0.0673295	total: 2m 5s	remaining: 53.5s
442:	learn: 0.0673258	total: 2m 5s	remaining: 53.2s
443:	learn: 0.0673251	total: 2m 6s	remaining: 52.8s
444:	learn: 0.0673251	total: 2m 6s	remaining: 52.5s
445:	learn: 0.0673228	total: 2m 6s	remaining: 52.2s
446:	learn: 0.0673220	total: 2m 6s	remaining: 51.9s
447:	learn: 0.0673214	total: 2m 7s	remaining: 51.6s
448:	learn: 0.0673214	total: 2m 7s	remaining: 51.2s
449:	learn: 0.0673213	total: 2m 7s	remaining: 50.9s
450:	learn: 0.0673182	total: 2m 7s	remaining: 50.6s
451:	learn: 0.0673174	total: 2m 7s	remaining: 50.3s
452:	learn: 0.0673168	total: 2m 8s	remaining: 50s
453:	learn: 0.0673158	total: 2m 8s	remaining: 49.8s
454:	learn: 0.0673154	total: 2m 8s	remaining: 49.5s
455:	learn: 0.0673134	total: 2m 9s	remaining: 49.2s
456:	learn: 0.0673129	total: 2m 9s	remaining: 49s
457:	learn: 0.0673124	total: 2m 10s	remaining: 48.9s
458:	learn: 0.0673117	total: 2m 10s	remaining: 48.6s
459:	learn: 0.0673087	total: 2m 10s	remaining: 48.4s
460:	learn: 0.0673059	total: 2m 11s	remaining: 48.1s
461:	learn: 0.0673050	total: 2m 11s	remaining: 47.8s
462:	learn: 0.0673050	total: 2m 11s	remaining: 47.5s
463:	learn: 0.0673043	total: 2m 11s	remaining: 47.2s
464:	learn: 0.0673033	total: 2m 12s	remaining: 46.9s
465:	learn: 0.0673006	total: 2m 12s	remaining: 46.6s
466:	learn: 0.0673000	total: 2m 12s	remaining: 46.3s
467:	learn: 0.0672993	total: 2m 12s	remaining: 46s
468:	learn: 0.0672970	total: 2m 13s	remaining: 45.7s

469:	learn: 0.0672963	total: 2m 13s	remaining: 45.4s
470:	learn: 0.0672948	total: 2m 13s	remaining: 45.1s
471:	learn: 0.0672938	total: 2m 13s	remaining: 44.8s
472:	learn: 0.0672915	total: 2m 14s	remaining: 44.5s
473:	learn: 0.0672916	total: 2m 14s	remaining: 44.2s
474:	learn: 0.0672911	total: 2m 14s	remaining: 43.9s
475:	learn: 0.0672886	total: 2m 14s	remaining: 43.6s
476:	learn: 0.0672880	total: 2m 14s	remaining: 43.3s
477:	learn: 0.0672878	total: 2m 15s	remaining: 43s
478:	learn: 0.0672878	total: 2m 15s	remaining: 42.6s
479:	learn: 0.0672857	total: 2m 15s	remaining: 42.3s
480:	learn: 0.0672829	total: 2m 15s	remaining: 42s
481:	learn: 0.0672828	total: 2m 15s	remaining: 41.7s
482:	learn: 0.0672818	total: 2m 16s	remaining: 41.4s
483:	learn: 0.0672806	total: 2m 16s	remaining: 41.1s
484:	learn: 0.0672798	total: 2m 16s	remaining: 40.8s
485:	learn: 0.0672781	total: 2m 16s	remaining: 40.5s
486:	learn: 0.0672775	total: 2m 16s	remaining: 40.2s
487:	learn: 0.0672760	total: 2m 17s	remaining: 39.9s
488:	learn: 0.0672743	total: 2m 17s	remaining: 39.6s
489:	learn: 0.0672729	total: 2m 17s	remaining: 39.3s
490:	learn: 0.0672727	total: 2m 17s	remaining: 39.1s
491:	learn: 0.0672703	total: 2m 18s	remaining: 38.8s
492:	learn: 0.0672698	total: 2m 18s	remaining: 38.5s
493:	learn: 0.0672689	total: 2m 18s	remaining: 38.2s
494:	learn: 0.0672685	total: 2m 19s	remaining: 38s
495:	learn: 0.0672661	total: 2m 19s	remaining: 37.7s
496:	learn: 0.0672659	total: 2m 19s	remaining: 37.4s
497:	learn: 0.0672651	total: 2m 20s	remaining: 37.3s
498:	learn: 0.0672645	total: 2m 20s	remaining: 37s
499:	learn: 0.0672639	total: 2m 21s	remaining: 36.7s
500:	learn: 0.0672627	total: 2m 21s	remaining: 36.4s
501:	learn: 0.0672616	total: 2m 21s	remaining: 36.2s
502:	learn: 0.0672611	total: 2m 22s	remaining: 35.9s
503:	learn: 0.0672599	total: 2m 22s	remaining: 35.6s
504:	learn: 0.0672579	total: 2m 22s	remaining: 35.3s
505:	learn: 0.0672561	total: 2m 22s	remaining: 35s
506:	learn: 0.0672527	total: 2m 23s	remaining: 34.7s
507:	learn: 0.0672517	total: 2m 23s	remaining: 34.4s
508:	learn: 0.0672504	total: 2m 23s	remaining: 34.1s
509:	learn: 0.0672499	total: 2m 23s	remaining: 33.8s
510:	learn: 0.0672480	total: 2m 24s	remaining: 33.6s
511:	learn: 0.0672460	total: 2m 24s	remaining: 33.3s
512:	learn: 0.0672442	total: 2m 24s	remaining: 33s
513:	learn: 0.0672436	total: 2m 24s	remaining: 32.7s
514:	learn: 0.0672420	total: 2m 25s	remaining: 32.4s
515:	learn: 0.0672420	total: 2m 25s	remaining: 32.1s
516:	learn: 0.0672411	total: 2m 25s	remaining: 31.8s
517:	learn: 0.0672395	total: 2m 25s	remaining: 31.5s
518:	learn: 0.0672384	total: 2m 25s	remaining: 31.2s
519:	learn: 0.0672371	total: 2m 26s	remaining: 30.9s
520:	learn: 0.0672350	total: 2m 26s	remaining: 30.6s
521:	learn: 0.0672346	total: 2m 26s	remaining: 30.3s
522:	learn: 0.0672328	total: 2m 26s	remaining: 30.1s
523:	learn: 0.0672323	total: 2m 27s	remaining: 29.8s
524:	learn: 0.0672303	total: 2m 27s	remaining: 29.5s
525:	learn: 0.0672298	total: 2m 27s	remaining: 29.2s
526:	learn: 0.0672294	total: 2m 27s	remaining: 28.9s
527:	learn: 0.0672270	total: 2m 28s	remaining: 28.6s
528:	learn: 0.0672268	total: 2m 28s	remaining: 28.4s
529:	learn: 0.0672241	total: 2m 28s	remaining: 28.1s
530:	learn: 0.0672237	total: 2m 29s	remaining: 27.8s
531:	learn: 0.0672235	total: 2m 29s	remaining: 27.5s
532:	learn: 0.0672228	total: 2m 29s	remaining: 27.2s
533:	learn: 0.0672222	total: 2m 29s	remaining: 27s
534:	learn: 0.0672215	total: 2m 30s	remaining: 26.7s
535:	learn: 0.0672198	total: 2m 30s	remaining: 26.4s
536:	learn: 0.0672174	total: 2m 31s	remaining: 26.2s
537:	learn: 0.0672168	total: 2m 31s	remaining: 25.9s
538:	learn: 0.0672159	total: 2m 32s	remaining: 25.7s
539:	learn: 0.0672148	total: 2m 32s	remaining: 25.4s
540:	learn: 0.0672142	total: 2m 32s	remaining: 25.1s
541:	learn: 0.0672116	total: 2m 32s	remaining: 24.8s
542:	learn: 0.0672098	total: 2m 33s	remaining: 24.5s
543:	learn: 0.0672092	total: 2m 33s	remaining: 24.2s
544:	learn: 0.0672077	total: 2m 33s	remaining: 24s
545:	learn: 0.0672071	total: 2m 33s	remaining: 23.7s
546:	learn: 0.0672057	total: 2m 34s	remaining: 23.4s
547:	learn: 0.0672045	total: 2m 34s	remaining: 23.1s
548:	learn: 0.0672035	total: 2m 34s	remaining: 22.8s
549:	learn: 0.0672032	total: 2m 34s	remaining: 22.5s
550:	learn: 0.0672016	total: 2m 35s	remaining: 22.2s
551:	learn: 0.0672013	total: 2m 35s	remaining: 21.9s
552:	learn: 0.0671991	total: 2m 35s	remaining: 21.7s
553:	learn: 0.0671982	total: 2m 35s	remaining: 21.4s
554:	learn: 0.0671975	total: 2m 36s	remaining: 21.1s
555:	learn: 0.0671964	total: 2m 36s	remaining: 20.8s
556:	learn: 0.0671964	total: 2m 36s	remaining: 20.5s
557:	learn: 0.0671942	total: 2m 36s	remaining: 20.2s
558:	learn: 0.0671930	total: 2m 37s	remaining: 20s
559:	learn: 0.0671926	total: 2m 37s	remaining: 19.7s
560:	learn: 0.0671916	total: 2m 37s	remaining: 19.4s
561:	learn: 0.0671900	total: 2m 37s	remaining: 19.1s
562:	learn: 0.0671881	total: 2m 38s	remaining: 18.8s
563:	learn: 0.0671852	total: 2m 38s	remaining: 18.5s
564:	learn: 0.0671845	total: 2m 38s	remaining: 18.2s
565:	learn: 0.0671838	total: 2m 38s	remaining: 18s
566:	learn: 0.0671816	total: 2m 39s	remaining: 17.7s
567:	learn: 0.0671792	total: 2m 39s	remaining: 17.4s
568:	learn: 0.0671783	total: 2m 39s	remaining: 17.1s
569:	learn: 0.0671770	total: 2m 39s	remaining: 16.8s
570:	learn: 0.0671763	total: 2m 40s	remaining: 16.6s
571:	learn: 0.0671759	total: 2m 40s	remaining: 16.3s
572:	learn: 0.0671748	total: 2m 40s	remaining: 16s
573:	learn: 0.0671723	total: 2m 41s	remaining: 15.7s
574:	learn: 0.0671704	total: 2m 41s	remaining: 15.4s
575:	learn: 0.0671681	total: 2m 42s	remaining: 15.2s
576:	learn: 0.0671672	total: 2m 42s	remaining: 14.9s
577:	learn: 0.0671664	total: 2m 42s	remaining: 14.7s
578:	learn: 0.0671640	total: 2m 43s	remaining: 14.4s
579:	learn: 0.0671632	total: 2m 43s	remaining: 14.1s
580:	learn: 0.0671629	total: 2m 43s	remaining: 13.8s
581:	learn: 0.0671605	total: 2m 43s	remaining: 13.5s
582:	learn: 0.0671587	total: 2m 44s	remaining: 13.2s
583:	learn: 0.0671569	total: 2m 44s	remaining: 13s
584:	learn: 0.0671554	total: 2m 44s	remaining: 12.7s
585:	learn: 0.0671535	total: 2m 45s	remaining: 12.4s
586:	learn: 0.0671525	total: 2m 45s	remaining: 12.1s
587:	learn: 0.0671513	total: 2m 45s	remaining: 11.8s
588:	learn: 0.0671505	total: 2m 45s	remaining: 11.5s
589:	learn: 0.0671493	total: 2m 46s	remaining: 11.3s
590:	learn: 0.0671469	total: 2m 46s	remaining: 11s
591:	learn: 0.0671465	total: 2m 46s	remaining: 10.7s
592:	learn: 0.0671454	total: 2m 46s	remaining: 10.4s
593:	learn: 0.0671449	total: 2m 47s	remaining: 10.1s
594:	learn: 0.0671438	total: 2m 47s	remaining: 9.84s
595:	learn: 0.0671438	total: 2m 47s	remaining: 9.55s
596:	learn: 0.0671412	total: 2m 47s	remaining: 9.27s
597:	learn: 0.0671398	total: 2m 47s	remaining: 8.99s
598:	learn: 0.0671394	total: 2m 48s	remaining: 8.7s
599:	learn: 0.0671370	total: 2m 48s	remaining: 8.42s
600:	learn: 0.0671356	total: 2m 48s	remaining: 8.14s
601:	learn: 0.0671354	total: 2m 48s	remaining: 7.86s
602:	learn: 0.0671338	total: 2m 49s	remaining: 7.58s
603:	learn: 0.0671332	total: 2m 49s	remaining: 7.29s
604:	learn: 0.0671324	total: 2m 49s	remaining: 7.01s
605:	learn: 0.0671302	total: 2m 49s	remaining: 6.73s
606:	learn: 0.0671284	total: 2m 50s	remaining: 6.45s
607:	learn: 0.0671277	total: 2m 50s	remaining: 6.17s
608:	learn: 0.0671264	total: 2m 50s	remaining: 5.89s
609:	learn: 0.0671259	total: 2m 51s	remaining: 5.61s
610:	learn: 0.0671248	total: 2m 51s	remaining: 5.33s
611:	learn: 0.0671237	total: 2m 51s	remaining: 5.05s
612:	learn: 0.0671220	total: 2m 51s	remaining: 4.77s
613:	learn: 0.0671217	total: 2m 52s	remaining: 4.5s
614:	learn: 0.0671196	total: 2m 53s	remaining: 4.22s
615:	learn: 0.0671185	total: 2m 53s	remaining: 3.94s
616:	learn: 0.0671178	total: 2m 53s	remaining: 3.66s
617:	learn: 0.0671156	total: 2m 54s	remaining: 3.38s
618:	learn: 0.0671134	total: 2m 54s	remaining: 3.1s
619:	learn: 0.0671112	total: 2m 54s	remaining: 2.82s
620:	learn: 0.0671077	total: 2m 54s	remaining: 2.53s
621:	learn: 0.0671061	total: 2m 55s	remaining: 2.25s
622:	learn: 0.0671052	total: 2m 55s	remaining: 1.97s
623:	learn: 0.0671045	total: 2m 55s	remaining: 1.69s
624:	learn: 0.0671023	total: 2m 55s	remaining: 1.41s

625:	learn: 0.0670998	total: 2m 56s	remaining: 1.13s
626:	learn: 0.0670993	total: 2m 56s	remaining: 844ms
627:	learn: 0.0670982	total: 2m 56s	remaining: 563ms
628:	learn: 0.0670957	total: 2m 57s	remaining: 281ms
629:	learn: 0.0670941	total: 2m 57s	remaining: 0us

In [39]:
submission = pd.DataFrame({
    'ParcelId': test_df['ParcelId'],
})
test_dates = {
    '201610': pd.Timestamp('2016-09-30')
}
for label, test_date in test_dates.items():
    print("Predicting for: %s ... " % (label))
    submission[label] = y_pred
    
submission.to_csv(data_path + 'Model_1_CatBoost.csv', float_format='%.6f',index=False)

Predicting for: 201610 ...

In [40]:
predictions_model_1 = pd.read_csv(data_path + 'Model_1_CatBoost.csv')
predictions_model_1.head()

   ParcelId    201610
0  10754147  0.032501
1  10759547  0.019552
2  10843547  0.023873
3  10859147  0.028043
4  10879947  0.022190